### ISSUE TITLE
Add "remove-shadow-dom-root-element" scriptlet

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/Scriptlets#103]
Check it out:
https://github.com/AdguardTeam/Scriptlets/issues/34#issuecomment-729342118

Don't forget about aliases as well.

**Comment by Stevoisiak** [comment]
Is there documentation on how to use `remove-shadow-dom-root-element`?

**Comment by slvvko** [comment]
@Stevoisiak 
https://github.com/AdguardTeam/Scriptlets/blob/master/wiki/about-scriptlets.md#remove-in-shadow-dom
