### ISSUE TITLE
Update redirect resources compatibility

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/Scriptlets#108]
Check this commit: https://github.com/gorhill/uBlock/commit/0b5f53923fc4fd7e6927ce57cd9226a61bcbdb88

We may need to check what ABP $rewrite resource aliases are missing.

**Comment by slavaleleka** [comment]
it's been a while since new [ABP redirect resources](https://raw.githubusercontent.com/adblockplus/adblockpluscore/master/data/resources.json) appeared. and [we already have](https://uploads.adguard.com/slbdzdrrnzmc.png) all of them
