### ISSUE TITLE
Implement analog for uBO's no-fetch-if scriptlet

### ISSUE THREAD

**Issue by slavaleleka** [AdguardTeam/Scriptlets#109]
https://github.com/gorhill/uBlock/commit/ba11a700139bbc648e4ae5b2bc7af90ef03db5df

\+ update compatibility with all other uBO scriptlets since few of them have been removed

**Comment by ameshkov** [comment]
See the relevant discussion here and some examples here: https://github.com/bogachenko/fuckfuckadblock/issues/101#issuecomment-753854137
