### ISSUE TITLE
prevent-setTimeout doesn't work on some websites

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/Scriptlets#110]
Steps to reproduce:
1. Disable all filter lists and add this rule:
`dobreprogramy.pl,example.org#%#//scriptlet('prevent-setTimeout')`
2. Go here -  [https://www.dobreprogramy.pl/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://www.dobreprogramy.pl/)
3. Open devtools and run this script:
```
setTimeout(function test() {
  console.log("test");
}, 1);
```

There should be a log info, but it doesn't work.

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/102932312-536c6180-44a0-11eb-9461-4a2a9fba45f4.png)

</details>

On http://example.org/ it works fine.

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/102932462-a0e8ce80-44a0-11eb-8e18-ae277ab1498a.png)

</details>

The same for preventing - `dobreprogramy.pl,example.org#%#//scriptlet('prevent-setTimeout', 'test')`, works fine on `example.org`, but doesn't work on `dobreprogramy.pl`.

**Comment by AdamWr** [comment]
Similar issue with `prevent-setInterval`.

Link - [https://www.bendigoadvertiser.com.au/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://www.bendigoadvertiser.com.au/)
Rule:
`example.org,bendigoadvertiser.com.au#%#//scriptlet('prevent-setInterval')`

I might be wrong, but in this case it looks like `setInterval` function is overridden by website.
<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/102946840-19ac5280-44c2-11eb-8af4-4e2ce5723c42.png)

</details>

And for example this is not displayed in the log:
<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/102947022-a5be7a00-44c2-11eb-8e0a-dacedd3cb890.png)

</details>

**Comment by llacb47** [comment]
@AdamWr yes, that site is using Newrelic's snippet which is overwriting `setInterval`.

More info here about newrelic: 

```
https://docs.newrelic.com/docs/browser/new-relic-browser/page-load-timing-resources/instrumentation-browser-monitoring
https://docs.newrelic.com/docs/browser/browser-monitoring/installation/install-browser-monitoring-agent
```

We've encountered the same in uBo as well.

```
https://github.com/uBlockOrigin/uAssets/issues/1639#issuecomment-633335338
https://github.com/uBlockOrigin/uAssets/issues/4526#issuecomment-451164840
```

What is the best solution?

**Comment by AdamWr** [comment]
Thank you for the information.
>We've encountered the same in uBo as well.
>```
>https://github.com/uBlockOrigin/uAssets/issues/1639#issuecomment-633335338
>https://github.com/uBlockOrigin/uAssets/issues/4526#issuecomment-451164840
>```

It seems that it's not actual already and uBlock Origin logs these information, I guess because uBO uses Proxy in scriptlets -https://github.com/gorhill/uBlock/blob/b6ed83bc5c840431ed03cddaed1daeb395db3b0e/assets/resources/scriptlets.js#L864
