### ISSUE TITLE
Improve set-cookie scriptlet with optional page reload

### ISSUE THREAD

**Issue by superlex** [AdguardTeam/Scriptlets#111]
Some sites need to be reloaded after a cookie was set. 

An option to reload the page could be added to scriptlet syntax.
Example:

`example.org#%#//scriptlet('set-cookie', 'checking', 'ok', 'reload')`

equivalent to

`example.org#%#(function(){-1==document.cookie.indexOf("checking")&&(document.cookie="checking=ok; path=/;",location.reload())})();`

**Comment by ameshkov** [comment]
We need an example of such a website

**Comment by superlex** [comment]
Correct me if I'm wrong:

example website: `it.readly.com`

Using
`readly.com#%#//scriptlet('set-cookie', 'ReadlyCookieConsent', '1')`
you need to manually reload the page, so you have to use
`readly.com#%#(function(){-1==document.cookie.indexOf("ReadlyCookieConsent")&&(document.cookie="ReadlyCookieConsent=1; path=/;",location.reload())})();`
instead.

**Comment by ameshkov** [comment]
Yeah, it seems to be the case, thank you!

**Comment by superlex** [comment]
You're welcome, thanks to you :)
