### ISSUE TITLE
Improve adjust-setInterval and adjust-setTimeout

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/Scriptlets#115]
I think that it would be nice to have an option to use `adjust-setInterval`/`adjust-setTimeout` without specified `timeout`.
I mean, if there is script like this:
```js
function getRandomInt(min, max) {
    min = Math.ceil(min);
    max = Math.floor(max);
    return Math.floor(Math.random() * (max - min + 1)) + min;
}
var random = getRandomInt(1000, 2000);

function test() {
 alert(1);
}
window.setTimeout(test, random);
```
then we will not be able to use `adjust-setTimeout`, because `timeout` is "randomized".

**Comment by slavaleleka** [comment]
@ameshkov should we handle `timeout` parameter as `1000..2000` for range or just `*` for any timeout delay?
