### ISSUE TITLE
televizeseznam.cz is broken by 'abort-current-inline-script'

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/Scriptlets#116]
@adguard-bot commented on [Sat Jan 30 2021](https://github.com/AdguardTeam/AdguardFilters/issues/73603)

### Issue URL (Ads)
 [https://www.televizeseznam.cz/video/cernota/cernota-dalsi-serie-z-temneho-podsveti-o-cem-tentokrat-63787580](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.televizeseznam.cz%2Fvideo%2Fcernota%2Fcernota-dalsi-serie-z-temneho-podsveti-o-cem-tentokrat-63787580)
### Comment
> 

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/h12W8rQ.jpg)
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard Browser extension v3.5.31
Browser: | EdgeChromium
Filters: | <b>Ad Blocking:</b><br/> AdGuard Base<br/><br/><b>Privacy:</b><br/> AdGuard Tracking Protection, <br/>EasyPrivacy<br/><br/><b>Social Widgets:</b><br/> AdGuard Social Media<br/><br/><b>Annoyances:</b><br/> AdGuard Annoyances<br/><br/><b>Language-specific:</b><br/> EasyList Czech and Slovak

**Comment by Alex-302** [comment]
uBO's rule from CZ filter breaks player when it used in AdGuard. In uBO player is not broken.
`televizeseznam.cz##+js(abort-current-inline-script, String.fromCharCode)`
Disable exclusion before check: `televizeseznam.cz#@%#//scriptlet('ubo-acis.js', 'String.fromCharCode')`

**Comment by AdamWr** [comment]
It looks like that it's similar issue as here - https://github.com/AdguardTeam/Scriptlets/issues/57#issuecomment-697240649
https://github.com/AdguardTeam/Scriptlets/issues/57#issuecomment-701542176

**Comment by stanislav-atr** [comment]
Fixed [here](https://github.com/AdguardTeam/Scriptlets/commit/c2d7378e4de8ed79fcd7cc17c0e883e48dcd2f2a).
