### ISSUE TITLE
Add localStorage and sessionStorage support

### ISSUE THREAD

**Issue by bestpika** [AdguardTeam/Scriptlets#118]
Some websites do not write the settings in cookies but in localStorage or sessionStorage, so is it possible to add support for these two storage areas?

Thank you.

**Comment by ameshkov** [comment]
@stanislav-atr let's start with a spec. The scriptlet we need should be similar to `set-constant`/`set-cookie`.
I suppose we should implement two scriptlets: `set-local-storage-item` and `set-session-storage-item`.

**Comment by stanislav-atr** [comment]
I guess storage scriptlets could look like this: 

<b>`example.com#%#//scriptlet('set-local-storage', 'name', 'value')`</b>

and similiar 

<b>`example.com#%#//scriptlet('set-session-storage', 'name', 'value')`</b>

- name — required, key name to be set.
- value —  required, it seems that most frequent data types for storage values are: 
  - boolean true/false
  - strings, including empty string
  - positive whole numbers
  - undefined
  - null
  - objects, including empty objects and nested objects
  - arrays, including empty arrays

There might be the need to implement JS expressions like `((new Date).getTime() + 6048E5).toString())` as key values.

**Comment by ameshkov** [comment]
> There might be the need to implement JS expressions like ((new Date).getTime() + 6048E5).toString()) as key values.

Can't you set a huge positive number instead of that?

**Comment by stanislav-atr** [comment]
@ameshkov there are JS rules like this,
`localStorage.setItem("ch:overlay.closed.time", "5000000000000")`
`localStorage.setItem('rnews.disablePopups', '9999999999999')`
so, i guess it is possible, but some website's scripts might need specific values tied to current Date, maybe?

**Comment by ameshkov** [comment]
@stanislav-atr not sure about that, it'd be better to check some real examples.

**Comment by stanislav-atr** [comment]
@ameshkov, i couldn't find the rules that require specific/current Date, i guess we can leave that implementation for JS rules.
