### ISSUE TITLE
Make uBlock's abort-on-stack-trace compatible to AdGuard

### ISSUE THREAD

**Issue by Yuki2718** [AdguardTeam/Scriptlets#120]
Inverse of https://github.com/AdguardTeam/FiltersCompiler/issues/104 This is harder to test but I'm pretty sure it's not compatible yet.

**Comment by stanislav-atr** [comment]
<b>`example.com#%#//scriptlet('abort-on-stack-trace', property[, stack])`</b>

- `property` — required, path to a property (_do we need chaining here?_). The property must be attached to `window`.
- `stack` —  required, string that must match the current function call stack trace.

It would be different from `abort-on-property-write` & `abort-on-property-read` by `stack` being required parameter and watching both getter and setter of the prop.

@ameshkov, @slavaleleka, take a look, please.

**Comment by ameshkov** [comment]
Yep, looks good.
