### ISSUE TITLE
Why can't I set the cookie value to a number greater than 15?

### ISSUE THREAD

**Issue by bestpika** [AdguardTeam/Scriptlets#121]
As the title, is this to prevent me from skipping the 18-year-old verification?

**Comment by tasi788** [comment]
I also have a related problem here.
With some websites where the cookie is placed with a custom value, but `set-cookie` only can set "possible values".

**Comment by slavaleleka** [comment]
we do not circumvent age restriction 

but this case is not related to skipping 18-year-old verification. it's dangerous to provide an option to set an arbitrary cookie,  so we made `set-cookie` scriptlet similar to `set-constant` with possible values which where the most used in filter lists https://github.com/AdguardTeam/Scriptlets/issues/79

**Comment by bestpika** [comment]
@slavaleleka I know that, but I need to get the site to skip the age limit now, so I need the 18 number.
And your company ask us to use the scriptlet to write the relevant cookie function when you add the FutaFilter, so we can't use that rule.

**Comment by tasi788** [comment]
> we do not circumvent age restriction
> 
> but this case is not related to skipping 18-year-old verification. it's dangerous to provide an option to set an arbitrary cookie, so we made `set-cookie` scriptlet similar to `set-constant` with possible values which where the most used in filter lists #79

maybe add "trusted filters" restriction before scriptlet run ? just like Javascript rules

**Comment by bestpika** [comment]
Also, I don't understand why the AG has to limit the value of cookies that can be used by this filter if I already trust the filter.

**Comment by ameshkov** [comment]
If the filter is trusted, you can use JS rules for that. Regarding age verification circumvention, this is straight illegal to circumvent such limitations, please be careful.

> Also, I don't understand why the AG has to limit the value of cookies that can be used by this filter if I already trust the filter.

We may provide a different set of scriptlets for such cases (prefixed as `ag-trusted` or `trusted-`). Default scriptlets are supposed to be limited to be protected from any misuse.
