### ISSUE TITLE
Add click2load scriptlet support

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/Scriptlets#122]

**Comment by stanislav-atr** [comment]
I guess scriptlet usage should look like this:

**`||example.org$subdocument,redirect=click2load.html`**

What should we include as html contents for this widget?

@ameshkov, @maximtop

**Comment by ameshkov** [comment]
Let's ask @AlikhanAliev to come up with something. What bothers me more is that this redirect resource is special, you'll need to change the apps to support this click&load logic.
