### ISSUE TITLE
Add no-floc scriptlet

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/Scriptlets#124]
Basically, this is the same as `#%#//scriptlet('set-constant', 'document.interestCohort', 'undefined')`

However, it'd be nice to have it as a separate scriptlet in case if we decide to make some additional improvements: https://github.com/gorhill/uBlock/commit/bfdc81e9e400f7b78b2abc97576c3d7bf3a11a0b

**Comment by krystian3w** [comment]
Also this need use `*` aka "all URLs" for long range scriptlets in uBO:

https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#-aka-all-urls

without the "`*`" filter is ignored by latest uBO.

In aka "all URLs" I see glitch with use `generichide` - when this filter is disabled.

**Comment by ameshkov** [comment]
> In aka "all URLs" I see glitch with use generichide - when this filter is disabled.

Could you please file a bug report about that?

**Comment by krystian3w** [comment]
I reported into uBlock-Issues long time ago and `gorhill` marked this as normal behavior in uBO env.

I suppose uBO newer add support `:style()` and `+js()` as generic without use "`*##`".

All in all, I wonder if this one scriptlet is immune to generichide in both technologies (AdGuard / uBO).

**Comment by ameshkov** [comment]
Uh, I don't fully understand the usecase, could you please show the rules + expected result?

**Comment by gorhill** [comment]
> Basically, this is the same as

Not the same, and the reason I created it -- using `set-constant` causes code like `'interestCohort' in Document` to become `true` when the API was not present, and I fear this would cause undue breakage. `no-floc` overrides only if the API is present, and is more in-line with what is expected to happen when FLoC is disabled -- maybe some code out there will eventually will assume the API is present by just checking the browser/version.

**Comment by gorhill** [comment]
>  wonder if this one scriptlet is immune to generichide in both technologies

`generichide` affects cosmetic filtering, scriptlet injection is not cosmetic filtering.

**Comment by wout-codes** [comment]
> `generichide` affects cosmetic filtering, scriptlet injection is not cosmetic filtering.

This is what should be happening in AdGuard.
@ameshkov Take a look at this issue: https://github.com/AdguardTeam/AdguardFilters/issues/79855

**Comment by krystian3w** [comment]
Also for uBO in `tsurlfilter` should add the added `*` for uBo version file:


![Przechwytywanie](https://user-images.githubusercontent.com/35370833/114389159-f0a8ee00-9b94-11eb-9013-c66e01d52338.JPG)

**Comment by ameshkov** [comment]
@wout-codes unless we make a separate `$genericjsinject` modifier for this, I'd prefer to keep the current behavior.

> causes code like 'interestCohort' in Document to become true when the API was not present

@gorhill makes sense. I wonder wouldn't it be better to update `set-constant` and handle cases with `undefined` differently.

**Comment by gorhill** [comment]
> I wonder wouldn't it be better to update

I thought about maybe adding a new modifier parameter for "only if property exists" but I wasn't comfortable to expand just for the sake of the FLoC case, which in the end I also use to determine whether the permission policy is to be injected.

**Comment by wout-codes** [comment]
> @wout-codes unless we make a separate `$genericjsinject` modifier for this, I'd prefer to keep the current behavior.

I suggest you to do it. Because `##` and `#%#` are completely different. `generichide` should only disable cosmetic.

**Comment by c2xusnpq6** [comment]
![image](https://user-images.githubusercontent.com/75058881/114557027-d7d73000-9c9b-11eb-8ac5-592d1db4d951.png)
