### ISSUE TITLE
Add correct translate escaped comma `\,` in `ra.js`/`rc.js` to AG syntax

### ISSUE THREAD

**Issue by krystian3w** [AdguardTeam/Scriptlets#133]
See "invalid selector":

https://github.com/AdguardTeam/FiltersRegistry/blob/de1e8c6c3aa186d5f84ac3bc3713459b05ffb7cc/filters/ThirdParty/filter_221_PolskiFiltrSocial/diff.txt#L279-L280

```js
forums-pl.ubisoft.com##+js(ra, href, area[href*="discordapp.com/"]\, area[href*="facebook.com/"]\, area[href*="instagram.com/"]\, area[href*="plus.google.com/"]\, area[href*="reddit.com/"]\, area[href*="twitter.com/"]\, area[href*="youtube.com/"])
```

so these should be translated into:

```css
forums-pl.ubisoft.com#%#//scriptlet('remove-attr', 'href', 'area[href*="discordapp.com/"], area[href*="facebook.com/"], area[href*="instagram.com/"], area[href*="plus.google.com/"], area[href*="reddit.com/"], area[href*="twitter.com/"], area[href*="youtube.com/"]')
```

About use "`\,`": 

> * "String" parameter means plain character(s)/word(s), quotes will be taken literally, commas [must be escaped](https://github.com/uBlockOrigin/uAssets/commit/2bec415a9bc4f81b29be3bf083ef1a20552f39db#commitcomment-29327114) in regex literals: `/foo\x2cbar\u002cbaz/`, after [1.22.0](https://github.com/gorhill/uBlock/commit/d67340f14db6ce5b446ef0ff4586b5e4d31f1086#diff-b03ba512faa0934947e57d28dc99b43bL242) commas can be escaped by backslash character (`foo\,bar`).
>
>> https://github.com/gorhill/uBlock/wiki/Resources-Library

**Comment by slavaleleka** [comment]
it should be double escaped for AdGuard:
`selector\\, another_selector`

**Comment by krystian3w** [comment]
So I must duplicate filter for AG only?

Like this:

```
forums-pl.ubisoft.com##+js(ra, href, area[href*="discordapp.com/"]\\, area[href*="facebook.com/"]
```

And this will work in uBO?
