### ISSUE TITLE
Add new scriptlet — trusted version of 'set-constant' for none-predefined values

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/Scriptlets#137]
Some of `AG_defineProperty` rules can't be converted to scriptlets, because in `set-constant` scriptlet we can use only predefined values, so I think that it would be nice if could use not only predefined values.

For example, maybe adding something like `#%#//ag-scriptlet` will be okay and it will be restricted to use it only in AdGuard filters, the same like `$replace` and other JS (`#%#`) rules.
`example.org#%#//ag-scriptlet("set-constant", "property", "value")`

https://github.com/AdguardTeam/AdguardFilters/issues/88860
```
! Can't be changed to scriptlet, because in scriptlet we can use only predefined values, so it can't be set to "FREECONTENT"
fashion.appledaily.com.tw#%#AG_defineProperty('options.subscriptionContent', { value: "FREECONTENT" });

! typeof salon_config.live_ads is a "string", so it can't be changed to a scriptlet
salon.com#%#AG_defineProperty('salon_config.live_ads', {value: "0"});

! Can't be changed to scriptlet, because in scriptlet we can use only predefined values, so it can't be set to "no"
ultimedia.com#%#AG_defineProperty('dtkPlayer.infos.autoplay', {value: "no"});

! Probably it will be possible to change this rule to scriptlet when this issue will be fixed - https://github.com/AdguardTeam/Scriptlets/issues/65
pewgame.com#%#AG_defineProperty('app_vars.counter_value', {value: 5, writable: false});

! Can't be changed to scriptlet, because in scriptlet we can use only predefined values, so it can't be set to "document.location.protocol"
tnaflix.com#%#AG_defineProperty('exoDocumentProtocol', { value: window.document.location.protocol });
pussyspace.com,pussyspace.net#%#AG_defineProperty('exoDocumentProtocol', { value: window.document.location.protocol });
nakedteens.fun#%#AG_defineProperty('exoDocumentProtocol', { value: window.document.location.protocol });
letfap.com#%#AG_defineProperty('exoDocumentProtocol', { value: window.document.location.protocol });
zbporn.com#%#AG_defineProperty('exoDocumentProtocol', { value: document.location.protocol });
porndroids.com#%#AG_defineProperty('exoDocumentProtocol', { value: window.document.location.protocol });

! Can't be changed to scriptlet, because in scriptlet we can use only predefined values, so it can't be set to "none"
gameflare.com#%#AG_defineProperty('GameflareAsdk.config.advert.network', {value: "none"});

```

**Comment by slavaleleka** [comment]
we will add new scriptlet `agtrusted-set-constant` to avoid predefined values 
due to https://github.com/AdguardTeam/Scriptlets/issues/106

**Comment by ameshkov** [comment]
Before we do that, are you sure there're no alternative solutions on all these websites?

**Comment by AdamWr** [comment]
We have alternative solutions for most of these rules, but sometimes it's not easy to find them and sometimes there may not be alternative solution (with current scriptlets).

**Comment by ameshkov** [comment]
The thing is that JS rules will be fully deprecated rather soon so we'd better find ones:)

**Comment by AdamWr** [comment]
We have a lot of JS rules, for example with `AG_onLoad` function, so it doesn't sound good.

**Comment by ameshkov** [comment]
Yep, we should gradually remove them all

**Comment by slavaleleka** [comment]
> ! typeof salon_config.live_ads is a "string", so it can't be changed to a scriptlet
> salon.com#%#AG_defineProperty('salon_config.live_ads', {value: "0"});

so we need a possibility to set the needed type of value?

**Comment by slavaleleka** [comment]
> #%#AG_defineProperty('exoDocumentProtocol', { value: window.document.location.protocol });

if I got it correctly, for such cases we need to get the value of `window.document.location.protocol` first, and after that to set the value to `exoDocumentProtocol`, right?

**Comment by krystian3w** [comment]
#65

**Comment by slavaleleka** [comment]
[Why do we need it](https://github.com/AdguardTeam/FiltersCompiler/issues/7#:~:text=maintained%20by%20us.-,Why%20do%20we%20need%20it,-JS%20rules%20are)

**Comment by krystian3w** [comment]
Bad link, incompatible with Firefox without Google WebExtension.
