### ISSUE TITLE
Add a redirect resource for piwik

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/Scriptlets#138]
Related - https://github.com/AdguardTeam/AdguardFilters/pull/90502

For example, this website is broken when piwik script is blocked - https://ec.europa.eu/eurostat/databrowser/view/demo_r_mwk_ts/default/table

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/128739416-706293cc-2e51-4feb-8d4d-76dbeafa7321.png)

</details>

May be helpful - https://gist.github.com/AdamWr/4382ed36f1873fb3e8b00892fe736ffd#file-ec_europa_eu_piwik-js

**Comment by stanislav-atr** [comment]
I am going to implement `prevent-piwik` following the example of `amazon-apstag` redirect so it should look like this:

**`||europa.eu/eurostat/databrowser/assets/analytics/piwik.js$script,redirect=prevent-piwik`**

**Comment by ameshkov** [comment]
@stanislav-atr let's write a scriptlet syntax description first and only then start implementing it.

First, let's start from the name. I suppose it should be simply called `matomo` (since Piwik was renamed).

**Comment by stanislav-atr** [comment]
@ameshkov, i still see the script as `piwik.js` on their [source repo](https://github.com/matomo-org/matomo/blob/4.x-dev/js/piwik.js). I still find `matomo` ok btw.

**Comment by ameshkov** [comment]
I suppose the scriptlet name should be the same as the system name, not a file name:)

**Comment by ameshkov** [comment]
Oh, my bad, of course it should be a redirect resource.

**Comment by stanislav-atr** [comment]
@ameshkov, i've edited the comment. Is there anything else we should consider?

**Comment by ameshkov** [comment]
Here's how a redirect resource description should look like:
https://github.com/AdguardTeam/Scriptlets/blob/master/wiki/about-redirects.md#google-analytics
