### ISSUE TITLE
Add Fingerprint2 surrogate script

### ISSUE THREAD

**Issue by Yuki2718** [AdguardTeam/Scriptlets#141]
~~Relevant case: https://github.com/AdguardTeam/AdguardFilters/issues/91230~~
The above doesn't require surrogate script. Here another one: https://github.com/AdguardTeam/AdguardFilters/issues/91255
Adding fingerprint2 redirect resource will allow filter authors to easily solve issues like the above without sacrificing user privacy.

**Comment by stanislav-atr** [comment]
**Redirect fingerprintjs.**
Mocks [FingerprintJS](https://github.com/fingerprintjs).

**Example**
`||the-japan-news.com/modules/js/lib/fgp/fingerprint2.js$script,`_`redirect=fingerprintjs`_

@ameshkov

**Comment by stanislav-atr** [comment]
@Yuki2718, could you, please, provide some more links with `fingerprint2.js?`
I don't see this script on `the-japan-news.com` atm.

**Comment by Yuki2718** [comment]
@stanislav-atr Wait a second please.

**Comment by Yuki2718** [comment]
@stanislav-atr Okay, this one from my personal list:
`https://gamerch.com/to-arise/`

<details>
<summary>Screenshot</summary>

![gamerch](https://user-images.githubusercontent.com/58900598/133645873-35a3e9ef-7a20-4b4f-b9c6-86689aaac221.png)

</details>

The highlighted comment form will be unresponsive if `gamerch.com/s3-assets/library/js/fingerprint2.min.js` is blocked without redirect.

**Comment by Yuki2718** [comment]
Here better example in which redirecting to noopjs doesn't work but fingerptin2 works: `https://gamebox.gesoten.com/casual/game/350`

<details>
<summary>Screenshot</summary>

![gesoten](https://user-images.githubusercontent.com/58900598/133647974-6c03388a-4a8e-4298-9f10-c8334b5ce8e1.png)

</details>

Don't care the game (it needs fix, I'll submit PR in EL soon) but scroll down and the ranking widget is responsive unless cdnjs.cloudflare.com/ajax/libs/fingerprintjs2/1.4.1/fingerprint2.min.js` is redirected.
