### ISSUE TITLE
Improve `prevent-addEventListener`

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/Scriptlets#143]
First issue, probably related to - https://github.com/AdguardTeam/Scriptlets/issues/110
If website overwrites `addEventListener` function then `prevent-addEventListener` scriptlet doesn't work.

Steps to reproduce:
1. Add these rules:
```
libri.link#@%#(function(){var b=document.addEventListener;document.addEventListener=function(c,a,d){if(a&&-1==a.toString().indexOf("adsBlocked"))return b(c,a,d)}.bind(window)})();
libri.link#%#//scriptlet("prevent-addEventListener", "click", "test")
libri.link#%#AG_onLoad(function() { document.body.addEventListener("click", function() { alert("test"); }); document.body.click(); });
```
2. Go to -  [https://libri.link/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://libri.link/)

Or add these rules:
```
example.org#%#//scriptlet("prevent-addEventListener", "click", "test")
example.org#%#(function(){var a=document.createElement("script");a.setAttribute("type","text/javascript");a.src="https://libri.link/cdn-cgi/scripts/7d0fa10a/cloudflare-static/rocket-loader.min.js";document.getElementsByTagName("head")[0].appendChild(a);a.onload=function(){document.body.addEventListener("click",function(){alert("test")});document.body.click()}})();
```
and go to - https://example.org/

Alert with "test" shouldn't be displayed.
<hr>

Second issue.
It seems that `log-addEventListener` doesn't work.

Steps to reproduce:
1. Add these rules:
```
example.org#%#//scriptlet('log-addEventListener')
example.org#%#AG_onLoad(function() { document.body.addEventListener("click", function() { alert("test"); }); document.body.click(); });
```
2. Go to - https://example.org/

`log-addEventListener` should print log into console, but doesn't work.
I guess that there is missed `log(logMessage);` here - https://github.com/AdguardTeam/Scriptlets/blob/master/src/scriptlets/log-addEventListener.js#L35

**Comment by slavaleleka** [comment]
so there are 3 cases:
1. scriptlet does not prevent addEventListener on libri.link
2. scriptlet does not prevent addEventListener cause by another user rule on example.org
3. scriptlet does not log addEventListener cause by another user rule on example.org

second and third will be fixed, but first one seems to be unfixable because of wrapping the callback needed for matching
https://uploads.adguard.com/slbdzdrveo33i.png

**Comment by AdamWr** [comment]
> so there are 3 cases:
> 
> 1. scriptlet does not prevent addEventListener on libri.link
> 2. scriptlet does not prevent addEventListener cause by another user rule on example.org

As I recall, first and second case are the same, in second case, the user rule loads `rocket-loader` script which override `EventTarget.prototype.addEventListener`.

> 3. scriptlet does not log addEventListener cause by another user rule on example.org

I think that it just doesn't work* and it's not caused by user rule.

*It works only with extension when filtering log is opened

**Comment by AdamWr** [comment]
By the way, what if we would add scriptlets for `window.addEventListener` and `document.addEventListener`, if I'm not wrong, it should at least partially fix first issue?

**Comment by slavaleleka** [comment]
yeah, it works, thanks!
