### ISSUE TITLE
Add no-xhr-if scriptlet

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/Scriptlets#146]
https://github.com/gorhill/uBlock/commit/745fbd1c02b7179052ba97f51c54f7cb000636f0

**Comment by ameshkov** [comment]
Why only xhr? Shouldn't we extend it to prevent `fetch` as well?

**Comment by AdamWr** [comment]
If I understand correctly, there is already `prevent-fetch` scriptlet -  https://github.com/AdguardTeam/Scriptlets/blob/master/wiki/about-scriptlets.md#prevent-fetch

**Comment by ameshkov** [comment]
Hmm, I don't yet understand the point of having two different scripts for two very similar things. If the syntax is the same in both of them, we could probably extend `prevent-fetch` to cover XHR as well and make `no-xhr-if` its alias.

@gorhill could you please explain why you made it a separate scriptlet and not extend the old one?

**Comment by gorhill** [comment]
I don't like the idea of having to patch the DOM more than needed, for this reason I prefer to keep `no-xhr-if` and `no-fetch-if` separate. But we can agree that the filter arguments are going to be the same, and in such case you can make `no-xhr-if` an alias of `no-fetch-if` on your side. In the next dev cycle, I may add a second argument for _behavior_, which will contains a list of space-separated tokens which will modify the behavior.

**Comment by ameshkov** [comment]
Thank you, the explanation makes sense to me.

**Comment by stanislav-atr** [comment]
`prevent-xhr` scriptlet: 

**`example.org#%#//scriptlet('prevent-xhr'[, propsToMatch])`**

- propsToMatch - optional, string of space-separated properties to match; possible props:
  - string or regular expression for matching the URL passed to `.open()` call; empty string or wildcard * for all fetch calls match
  - colon-separated pairs name:value where
    - name is XMLHttpRequest object property name
    - value is string or regular expression for matching the value of the option passed to fetch call

Also as with the `prevent-fetch` scriptlet:
> Usage with no arguments will log XMLHttpRequest objects to browser console; which is useful for debugging but permitted for production filter lists.

_Do we need matching by method? ("GET", "POST", "PUT", "DELETE")_

**Comment by slavaleleka** [comment]
we do need method matching:
1) it might be really helpful
2) for better compatibility with [ubo-scriptlet](https://github.com/gorhill/uBlock/wiki/Resources-Library#no-xhr-ifjs-)
