### ISSUE TITLE
Implement set-attr scriptlet

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/Scriptlets#147]
https://github.com/AdguardTeam/Scriptlets/blob/master/wiki/about-scriptlets.md#-%EF%B8%8F-remove-attr
For example [here](https://www.go-mp3.com/de27) when `data-fc` attribute is removed, download is not working. But works, when removed value of attribute. It seems oprional parameter can be added - `1` remove attr, `0` remove value only.
![image](https://user-images.githubusercontent.com/8361299/133988426-95e26f72-f71d-40c8-aecb-658cac2360c7.png)

**Comment by ameshkov** [comment]
Maybe let's consider `set-attr` instead? It could work the same way as the `set-constant` scriptlet.

**Comment by Alex-302** [comment]
Indeed. Thought it might be unsafe.

**Comment by ameshkov** [comment]
With a limited set of values it *should* be okay.

**Comment by slavaleleka** [comment]
so let's start with only one predefined value — empty string `''`, shall we? 
the list of values will be extended in future when we need it

**Comment by ameshkov** [comment]
@slavaleleka yup, sounds reasonable. @AdguardTeam/filters-maintainers are there any rules where other values might be needed?

**Comment by AdamWr** [comment]
If I understand correctly, it sounds like one of the points from this issue - https://github.com/AdguardTeam/Scriptlets/issues/106

> - setting HTML elements attributes, example: https://github.com/AdguardTeam/AdguardFilters/pull/69608

So maybe adding numbers will be useful.

**Comment by Alex-302** [comment]
And what about `agtrusted-` https://github.com/AdguardTeam/Scriptlets/issues/106#issuecomment-749503497 with no limits?

**Comment by ameshkov** [comment]
@AdamWr @Alex-302 tbh I don't see why we cannot allow setting arbitrary height or width for an element. This is not the same as allowing an arbitrary string.

For instance, we could allow doing something like this: `set-attr('height', '10px')` and allow any dimension there (`px`, `em`, anything else?).

**Comment by AdamWr** [comment]
Okay.
By the way, if I'm not wrong, `height` attribute doesn't need `px` (it's added by default) and it looks like that `em` doesn't work at all, but `%` seems to be supported.

**Comment by ameshkov** [comment]
@AdamWr yep, you're right, it only supports `px` or `%` (or no dimension which is the same as `px`).

**Comment by stanislav-atr** [comment]
**`example.org#%#//scriptlet('set-attr', 'name', 'value')`**

- name - required, a string specifying the name of the attribute whose value is to be set.
- value - required(?), the value to assign to the attribute.
  - `''` - empty string,
  - `any whole positive number` - for the ability to set `height` and `width` attributes. 

@AdamWr, percent is supported by height/width attributes but is only viable if the element's parent has correlated attribute set explicitly (in px), therefore i don't see much sense in supporting `%` here. [Also](https://stackoverflow.com/a/1622097):
```
If you want to make the div height a percentage of the viewport height, every ancestor of the div, including <html> and <body>, have to have height: 100%, so there is a chain of explicit percentage heights down to the div.
```

 We may also make `value` an optional argument, making `''` the default parameter.

@ameshkov, @slavaleleka

**Comment by ameshkov** [comment]
@stanislav-atr works for me, thank you!
