### ISSUE TITLE
Implement popular defusers

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/Scriptlets#15]
* `prevent-fab-3.2.0`: fuckadblock.js-3.2.0	
* `set-popads-dummy`:  popads-dummy.js	
* `prevent-popads-net`: popads.net.js	
* `prefent-adfly`: adfly-defuser.js

**Comment by Alex-302** [comment]
what about `setTimeout-defuser`?

**Comment by ameshkov** [comment]
https://github.com/AdguardTeam/Scriptlets#compatibility

**Comment by Alex-302** [comment]
ok
