### ISSUE TITLE
Fix or remove stack trace functionality of abort-on-property-read/write.

### ISSUE THREAD

**Issue by stanislav-atr** [AdguardTeam/Scriptlets#150]
The issue is that stack trace matching function is called in scriptlet context therefore always returning `true` for any `stack` argument: 
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/68852737/134633451-fec56cbd-4138-4057-9a9b-2fa531260eac.png)</details><br/>

when it should be called from target property context (example from `abort-on-stack-trace`):
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/68852737/134633745-d7aef7f9-0fb0-4215-95ba-61efcb792910.png)</details><br/>

I propose removing this functionality from `abort-on-property-*` scriptlets as

- we now have `abort-on-stack-trace` scriptlet for more accurate property access blocking
- fixing it instead of removing will make `abort-on-property-*` and `abort-on-stack-trace` scriptlets partly interchangeable

We have 586 rules with `abort-on-property-*` scriptlets in our filters and none of them use `stack` argument, so backward compatibility shouldn't be an issue here.

**Comment by ameshkov** [comment]
Since it's not used anywhere, we can indeed get rid of it.
