### ISSUE TITLE
remove-class/attr behavior parameter

### ISSUE THREAD

**Issue by slavaleleka** [AdguardTeam/Scriptlets#152]
@krystian3w commented on [Thu Sep 30 2021](https://github.com/AdguardTeam/FiltersCompiler/issues/124)

uBO finally added support dom tree observe by **optional** `, stay` parameter for both scriptles:

<ul><li>

https://github.com/uBlockOrigin/uBlock-issues/wiki/Resources-Library#rajs-

>` stay`: This tells the scriplet to stay active and act on document changes.

`example.com##+js(remove-attr, class, .j-mini-player, stay)`

Optionally newer uBO implemented combine `asap` with `stay`:

`example.com##+js(remove-attr, class, .j-mini-player, asap stay)`

https://github.com/gorhill/uBlock/commit/35d7406214e39fa5ad5c73cfab3eecb0eb7c8b7f + https://github.com/uBlockOrigin/uAssets/issues/9528

---

<li>

https://github.com/uBlockOrigin/uBlock-issues/wiki/Resources-Library#rajs-

> `stay`: This tells the scriplet to stay and act on DOM changes, while the default behavior is to act only once when the document becomes interactive.

`danskebank.fi##+js(rc, cookie-consent-banner-open, html, stay)`

`remove-class` for now may no support combine `, asap stay` - so uBO will have to detect a change in the DOM as if AdGuard were removing CSS classes much faster.

</ul>

---

This implementation in file for uBO should increase the compatibility of scripts in uBO, when AdGuard observes changes in the DOM tree by default.

**Comment by krystian3w** [comment]
https://github.com/AdguardTeam/Scriptlets/issues/245

**Comment by krystian3w** [comment]
https://github.com/AdguardTeam/FiltersCompiler/issues/124 https://github.com/AdguardTeam/Scriptlets/issues/152 https://github.com/AdguardTeam/Scriptlets/issues/245
