### ISSUE TITLE
abort-current-inline-script somehow aborts inline-script despite there should be no hit

### ISSUE THREAD

**Issue by Yuki2718** [AdguardTeam/Scriptlets#153]
At `https://www.rjno1.com/` anti-adb is triggered only on uBO (now fixed) and not on AG with Chinese filters, the reason seems to be AG interprets parameter in case-insensitive manner by default: `rjno1.com#%#//scriptlet("abort-current-inline-script", "onload", "adblock")` in Chinese filter doesn't work if interpreted in case-sensitive manner or should be changed from `adblock` to `AdBlock`. In this case the case-insensitivity works positively, but there may be edge-case this in turn causes problem.

**Comment by stanislav-atr** [comment]
`example.org#%#//scriptlet('abort-current-inline-script', property[, search])`

Scriptlet processes `search` string with case-sensitive function ( `toRegExp('Hello')` returns `/Hello/`)
```
const toRegExp = (str) => {
    if (!str || str === '') {
        const DEFAULT_VALUE = '.?';
        return new RegExp(DEFAULT_VALUE);
    }
    if (str[0] === '/' && str[str.length - 1] === '/') {
        return new RegExp(str.slice(1, -1));
    }
    const escaped = str.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
    return new RegExp(escaped);
};
```
 and then .test() the result against `content` string. @Yuki2718, are you sure case-(in)sensitivity is the issue here?

**Comment by Yuki2718** [comment]
@stanislav-atr I can't think of a better explanation that `rjno1.com#%#//scriptlet("abort-current-inline-script", "onload", "adblock")` works on the site.
Add
```
rjno1.com#@%#//scriptlet("abort-current-inline-script", "onload", "AdBlock")
rjno1.com#%#//scriptlet("abort-current-inline-script", "onload", "adblock")
```
and you can see - no small letters' `adblock` in their inline script.

**Comment by stanislav-atr** [comment]
@Yuki2718, what do you mean by
>abort-current-inline-script filter must be added

?

**Comment by Yuki2718** [comment]
I confirmed the issue is present only on `www.rjno1.com` and not on other sites - `search` parameter is working correctly on all the other sites. `abort()` throws reference error only if `searchRegexp.test(content)` is true so theoretically it can't be by this scriptlet. Nevertheless, `rjno1.com#%#//scriptlet("abort-current-inline-script", "onload", "whatever")` indeed works and `chd3dcheckguishow` on the site will not be overwritten to `true` only if this filter is added. Changing the first parameter (`property`) breaks this, but changing the second parameter (`search`) not.

**Comment by Yuki2718** [comment]
On my end `chd3drjno1adsjsload` is always true.

**Comment by stanislav-atr** [comment]
@Yuki2718, is this issue still relevant? I am getting adblock modal with any of these rules right now
```
rjno1.com#%#//scriptlet("abort-current-inline-script", "onload", "AdBlock")
rjno1.com#%#//scriptlet("abort-current-inline-script", "onload", "adblock")
```
and strangely these is no adb modal if i use
```
rjno1.com#%#//scriptlet("abort-current-inline-script", "onload", "randomstring")
```
This is most probably caused by some flaw in their adb code as `abort-current-inline-script` works as intended (being case-sensitive and creating hits only where intended).

**Comment by Yuki2718** [comment]
@stanislav-atr On my end `rjno1.com#%#//scriptlet("abort-current-inline-script", "onload", "AdBlock")` works, but as you said `rjno1.com#%#//scriptlet("abort-current-inline-script", "onload", "randomstring")` too. I think this can be closed anyway, not worth spending your time - the fix in Chinese filters is working.

**Comment by AdamWr** [comment]
I might be wrong, but I think that it's still relevant and it's not only related to this website.
Steps to reproduce:
1. Add these rules (it seems that in this case order matter, so a first added rule should be with `abort-current-inline-script`):
```
example.org#%#//scriptlet("abort-current-inline-script", "onload", "whateverBlablabla")
example.org#%#window.onload=()=>{alert("test")};
```
2. Go to - https://example.org/

`abort-current-inline-script` causes that `onload` function is not executed.

**Comment by stanislav-atr** [comment]
@AdamWr ty fo testing this. The thing is, scriptlet works as intended, but for some reason event-related properties (and not something like `console.log`) of window like `.onload`, `.onkeyup` etc are interrupted just by the fact of something setting new setter and getter (even though they technically don't interrupt normal flow, i've removed `abort()` function from scriptlet to test this). Any ideas on how could that be?

**Comment by AdamWr** [comment]
To be honest, I don't know, but maybe it's due to fact that `setPropertyAccess` function is using `Object.defineProperty` to set a property and in this case `onload` function is not executed.
It seems that adding `currentValue.call(base,prop);` below this line:
https://github.com/AdguardTeam/Scriptlets/blob/290401b69121607f82ee689c321795c21fda49ba/src/scriptlets/abort-current-inline-script.js#L147
causes that it works, but I'm just guessing and I'm not sure if it should be done this way.

**Comment by stanislav-atr** [comment]
@AdamWr adding `currentValue.call(base,prop);` technically works, but that calls for function immediately after being set, so window.onload gonna run on `document.readyState = 'loading' `and not `'complete'`, same for other 'on' listeners.

**Comment by AdamWr** [comment]
Maybe we could do something similar like in uBlock Origin - https://github.com/gorhill/uBlock/blob/b3f1f75389df03717d1c3f1cc918f1f6ebaacaa7/assets/resources/scriptlets.js#L117-L123

For example, add something like this:
```js
let currentValue = base[prop];
var currentDescriptor = Object.getOwnPropertyDescriptor(base, prop);
setPropertyAccess(base, prop, {
    set: (value) => {
        abort();
        if (currentDescriptor instanceof Object) {
            currentDescriptor.set.call(base, value);
        } else {
            currentValue = value;
        }
    },
    get: () => {
        abort();
        return currentValue;
    },
});
```
here:
https://github.com/AdguardTeam/Scriptlets/blob/290401b69121607f82ee689c321795c21fda49ba/src/scriptlets/abort-current-inline-script.js#L143-L153

**Comment by stanislav-atr** [comment]
That is a solution in a sense that it wont break props without match, but it wont abort newly created callbacks either: 
`example.org#%#//scriptlet("abort-current-inline-script", "onkeyup", "UP")
`

Then run `window.onkeyup=()=>{console.log("UP")};` in console. Scriptlet won't block `window.onkeyup` at all now.
I guess that's better than original issue though.

@slavaleleka, what do you think about this?

**Comment by AdamWr** [comment]
Doesn't it work like this already?
I mean, for example, if you have an inline script like this:
```js
<script>
window.test = ()=>console.log("TEST");
test();
</script>
```
and rule like this - `example.org#%#//scriptlet("abort-current-inline-script", "test")`
then it will be aborted, but if you run this script in console:
```js
window.test = ()=>console.log("TEST");
test();
```
it will works, or maybe I just don't understand what a problem is :)

**Comment by AdamWr** [comment]
I have checked it here - https://jsfiddle.net/9k46oq7c/
and it seems to works correctly. with something like this (I'm using modified `abortCurrentInlineScript` so it doesn't look exactly like this):
```
fiddle.jshell.net,example.org#%#//scriptlet("abort-current-inline-script", "onkeyup", "UP")
```

`onkeyup` function is aborted and `onload` works fine.

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/145418579-0d7ce10c-24bf-436d-9ec8-87a09036e3aa.png)

</details>

By the way, as far as I understand, if you are using something like `example.org#%#window.onload=()=>{alert("test")};` in user rules, then it shouldn't be blocked by `abort-current-inline-script`.

**Comment by stanislav-atr** [comment]
@AdamWr, what code fo u use for that? I'm still getting the results above.

**Comment by AdamWr** [comment]
It seems that current solution breaks `DDoS protection by Cloudflare`.
For example here - [https://1337x.st/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://1337x.st/)
Rule:
```
1337x.st#%#//scriptlet("abort-current-inline-script", "String.fromCharCode", "qwertyuiop_test")
```

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/147571945-149060fb-a722-4f6b-b53c-09aa9a1cebb2.png)

![image](https://user-images.githubusercontent.com/29142494/147572251-b137597a-e916-480b-8d57-39d0d8a90b5c.png)

</details>

As far as I understand, there is additional check in uBO which wasn't added.
https://github.com/gorhill/uBlock/blob/b3f1f75389df03717d1c3f1cc918f1f6ebaacaa7/assets/resources/scriptlets.js#L70-L77

Something like:
```
let origDescriptor = Object.getOwnPropertyDescriptor(owner, prop);

if (origDescriptor instanceof Object === false || origDescriptor.get instanceof Function === false) {
  origDescriptor = undefined;
}
```

**Comment by Alex-302** [comment]
Another case:
https://up-load.io/4l4zo2ep495c
captcha is broken by
`up-load.io#%#//scriptlet("abort-current-inline-script", "Math", "delete window")`
`up-load.io#%#//scriptlet("abort-current-inline-script", "String.fromCharCode", "/emZnbG9hZGVk|break;case \$\.|break;case \d{1}/")`
The first rule breaks it completely. Without the 1st, with the second rule captcha cannot be solved.

**Comment by stanislav-atr** [comment]
@Alex-302, is it still reproducible?
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/68852737/148742781-c728ea7f-b3dc-48ec-9938-5cdc164392f3.png)</details><br/>

**Comment by Alex-302** [comment]
@stanislav-atr add the rules.

**Comment by Alex-302** [comment]
Another case (`#%#//scriptlet("abort-current-inline-script", "String.fromCharCode", "constructor")`)
https://github.com/AdguardTeam/AdguardFilters/issues/105214

**Comment by Alex-302** [comment]
Not reproduced with new scriptlets version in ext. 4.0.94
