### ISSUE TITLE
coddyschool.com - broken site with metrics redirect

### ISSUE THREAD

**Issue by zloyden** [AdguardTeam/Scriptlets#163]
The same case as on the report https://github.com/AdguardTeam/AdguardFilters/issues/53442 if you use `||mc.yandex.ru/metrika/tag.js$script,redirect=metrika-yandex-tag,important`.

**Comment by AdamWr** [comment]
I'm not sure, but maybe adding:
```
window["yaCounter" + id] = api;
```
to this function:
https://github.com/AdguardTeam/Scriptlets/blob/7303f098b9fd71773134d9709fd21287c81eebd1/src/redirects/metrika-yandex-tag.js#L100-L102
could fix this issue.
