### ISSUE TITLE
tv.yandex is broken when using a redirect rule

### ISSUE THREAD

**Issue by zloyden** [AdguardTeam/Scriptlets#164]
There is a blank screen when using `||mc.yandex.ru/metrika/watch.js$script,important,redirect=metrika-yandex-watch`.
To reproduce it:
1. Add the rule above.
2. Open `tv.yandex.ru`.

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/33488229/144507797-fc2412c2-8e2a-4e2a-a828-2fb2e769f0ff.png)

</details><br/>

**Comment by AdamWr** [comment]
Similar issue on `disk.yandex.ru` and on `docviewer.yandex.ru` - https://github.com/AdguardTeam/AdguardFilters/issues/102052
If I'm not wrong, in that case adding:
```
Metrika.prototype.params = noopFunc;
```
should fixes this issue.

Steps to reproduce:
1. Add this rule:
```
||mc.yandex.ru/metrika/watch.js$script,important,redirect=metrika-yandex-watch
```
2. Go to - [https://disk.yandex.ru/d/odljb_kJMlhyKQ](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fdisk.yandex.ru%2Fd%2Fodljb_kJMlhyKQ)

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/144834254-3224dcc2-a172-417d-8f1a-4a8a0596451d.png)

</details>

It seems that the same/similar issue occurs on `docviewer.yandex.ru`.
