### ISSUE TITLE
auth.wi-fi.ru - broken site when using a redirect rule

### ISSUE THREAD

**Issue by zloyden** [AdguardTeam/Scriptlets#165]
There is a button on the screenshot that doesn't work.

To reproduce it:
1. Add `||mc.yandex.ru/metrika/watch.js$script,important,redirect=metrika-yandex-watch`.
2. Open `auth.wi-fi.ru`.
3. Click on the button from the screenshot.
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/33488229/144508442-b8dfaab1-70b6-4233-8c5a-b80f04f2da64.png)

</details><br/>

**Comment by stanislav-atr** [comment]
Same as #164
