### ISSUE TITLE
Add a redirect resource for `imasdk.googleapis.com/js/sdkloader/ima3.js`

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/Scriptlets#169]
I guess this might be useful - https://searchfox.org/mozilla-central/source/browser/extensions/webcompat/shims/google-ima.js

**Comment by krystian3w** [comment]
Legacy idea by jspenguin2017:

https://github.com/jspenguin2017/uBlockProtector/blob/master/src/resources/ima3.js

But dropped after detect too many glitches.
