### ISSUE TITLE
Improve `googletagservices-gpt` redirect resource

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/Scriptlets#174]
This website is broken - [https://www.weatherandradar.com/weather-map](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.weatherandradar.com%2Fweather-map) when `securepubads.g.doubleclick.net` is blocked or a redirect resource is used - `||securepubads.g.doubleclick.net/tag/js/gpt.js$script,redirect=googletagservices-gpt,important`

This solution - https://searchfox.org/mozilla-central/source/browser/extensions/webcompat/shims/google-publisher-tags.js seems to works fine, so maybe we could improve `googletagservices-gpt` redirect resource.

Steps to reproduce:
1. Add this rule:
```
||securepubads.g.doubleclick.net/tag/js/gpt.js$script,redirect=googletagservices-gpt,important
```
2. Go to - [https://www.weatherandradar.com/weather-map](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.weatherandradar.com%2Fweather-map)

Website is blank.

**Comment by Alex-302** [comment]
Probably related to this issue: 

https://www.thestar.co.uk/

broken player(see screenshot), even if request just blocked

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/8361299/147595267-3a5d72b2-f080-4d90-8a24-721a9e6e1389.png)

</details>

Before checking add `@@||googletagservices.com/tag/js/gpt.js$domain=thestar.co.uk,badfilter`
