### ISSUE TITLE
Improve `googlesyndication-adsbygoogle`

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/Scriptlets#184]
There is website - https://github.com/AdguardTeam/AdguardFilters/issues/106591 which is checking if `adsbygoogle.push.length === 1` (not only this) to detects ad blockers.
As far as I understand, if `pagead2.googlesyndication.com/pagead/js/adsbygoogle.js` is not blocked, then `adsbygoogle.push.length` by default returns `1`, so maybe we could change this line:
https://github.com/AdguardTeam/Scriptlets/blob/02f0e65ec5bc971db0f7179b5a8561837a6363d6/src/redirects/googlesyndication-adsbygoogle.js#L24
to something like:
```js
push(arg) { 
```

**Comment by ameshkov** [comment]
But what difference does it make?

**Comment by AdamWr** [comment]
Adding an argument to the function `adsbygoogle.push` will cause that `adsbygoogle.push.length` will return `1`.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/length

**Comment by ameshkov** [comment]
Ah, `push.length`, got it.

**Comment by AdamWr** [comment]
I wonder if could improve `adsbygoogle.push` function.
For example, this issue - https://github.com/AdguardTeam/AdguardFilters/issues/109127
It looks like that this website uses `adsbygoogle.push` to load games.

```js
window.adBreak = window.adConfig = function(o) {
    adsbygoogle.push(o);
}

window.adBreak({
    type: "preroll",
    name: "game",
    adBreakDone: (res) => {
        console.log("adBreakDone:", res);
        $("#adTitle").hide();
        SkipAdAndShowGame(); // then it calls showgame() functions which display game
    }
});
```

Something like this should works:
```js
window.adsbygoogle = {
  loaded: true,
  push: function (arg) {
    
    if (typeof this.length === 'undefined') {
      this.length = 0;
      this.length += 1;
    }

    if (arg !== null && arg instanceof Object && arg.constructor.name === "Object") {
      for (let key in arg) {
        if (typeof arg[key] === 'function') {
          try {
            arg[key].call();
          } catch (e) {
            console.error(e);
          }
        }
      }
    }
    
  }
};
```

By the way, maybe we could add (or re-add, if I'm not wrong, it was possible long time ago) an ability to use redirect resources as a scriptlets?
I think that it could be useful for extension for iOS/Safari and in case when user has DNS filtering enabled.
