### ISSUE TITLE
Improve `google-analytics` redirect resource

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/Scriptlets#185]
https://github.com/gorhill/uBlock/commit/fba680f9abb16ce567c24dd02f5edc53b543b159

Steps to reproduce
1. Add this rule:
```
||googletagmanager.com/gtm.js$third-party,script,redirect=googletagmanager-gtm
```
2. Navigate to -  [https://www.woolworths.co.za/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://www.woolworths.co.za/)

Website is broken.
<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/150955067-2d468b37-15d5-434d-b0b0-be407165a6d5.png)

</details>

**Comment by slavaleleka** [comment]
`google-analytics` should be fixed as [it covers `googletagmanager-gtm` functionality](https://github.com/AdguardTeam/Scriptlets/issues/127)
