### ISSUE TITLE
Add a redirectable script that sets canRunAds true

### ISSUE THREAD

**Issue by Yuki2718** [AdguardTeam/Scriptlets#190]
Related discussion: https://github.com/uBlockOrigin/uAssets/commit/036e13101ea60a14b4a416f47609793da7434b16
If this is added, we can add following very wide rules safely:
```
/prebid-ads.js$script,redirect=canrunads
/ads-prebid.js$script,redirect=canrunads
```
These should cover not only `bigbtc.win` but many more: https://publicwww.com/?q=%22%2Fprebid-ads.js%22+depth%3Aall See how many `/prebid-ads.js` or `/ads-prebid.js` rules are in Base filters.

**Comment by slavaleleka** [comment]
so this redirect should simply set constant?
```
canRunAds = true
```

**Comment by Yuki2718** [comment]
> so this redirect should simply set constant?
> 

Yes.

**Comment by Yuki2718** [comment]
Whoa, that is what I certainly missed. It needs evaluation then.

**Comment by Yuki2718** [comment]
A few more working cases:
```
hideandseek.world/js/prebid-ads.js
timebucks.com/publishers/js/prebid-ads.js
true-gaming.net/home/wp-content/themes/TrueGaming2021/js/prebid-ads.js
playmyopinion.com/assets/developer/js/prebid-ads.js
```
I think the resource is still overall worth, we just need to avoid `$important` so that non-working cases will not be affected if an exception is added. It won't negatively affect in those cases. Many of them create a random-id div or use an unique variable, but I found another commonly used variable of `isAdBlockActive`:
```
note.sieuthuthuat.com/js/prebid-ads.js
leaklinks.com/js/prebid-ads.js
getpaste.link/js/prebid-ads.js
sharetext.me/js/prebid-ads.js
vippaste.xyz/js/prebid-ads.js
```
Probably **setting `isAdBlockActive to false will improve its usefulness**. @cc @gorhill

**Comment by ameshkov** [comment]
Okay, there're two possible approaches:

1. One redirect stub that combines many constants in it (`constant-detection-stubs`)
2. Multiple stubs, one per constant (`constant-canrunads`, `constant-isadblockactive`)

Which one do you think is better?

CC @AdguardTeam/filters-maintainers

**Comment by Yuki2718** [comment]
I emphasize that the actual use will be generic filter. There's not much sense to use this only for specific domain as we can use and has been using scriptlet for that.

**Comment by AdamWr** [comment]
I would prefer one redirect (`constant-detection-stubs`) with two or few most popular/used constants, so it could cover more cases if it would be used as a generic rule.

**Comment by gorhill** [comment]
Personally I prefer one constant per stub, otherwise this causes a user to stand out as using a content blocker . i.e. a site could load a script which set `canRunAds` and then test if `isAdblockActive` is `true` to find out that the visitor is most certainly using a content blocker -- which then defeat the purpose of the stub.

**Comment by Yuki2718** [comment]
I actually considered about that but that's no worth than not using stub (no fix) - detected by blocking prebid-ads. We anyway can't hide the fact user is using content blocker as long as it blocks something.

**Comment by gorhill** [comment]
Ok I see, the same script file name is used as bait for either sentinel variables, and it wouldn't be possible to create a generic filter that set both variables with one single redirection.

**Comment by Yuki2718** [comment]
I made commits after the comment: https://github.com/gorhill/uBlock/commit/ef25f30b308398319978b011db847947ddfd89f0
