### ISSUE TITLE
set-constant scriptlet user rule is not working as expected

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/Scriptlets#191]
@BottledSoda commented on [Sat Feb 05 2022](https://github.com/AdguardTeam/AdguardForMac/issues/1036)

### Steps to reproduce

1. Add `powerclicks.xyz#%#//scriptlet("set-constant", "blurred", "false")
**(*##+js(set, ..., ....)* seemingly works as expected)**
2. Visit `https://powerclicks.xyz/P7w6J` and if possible, go to second page/step
3. When out-of-focus, seemingly, the countdown freezes

### Expected behavior

`blurred` should be set to `false` and thus the countdown shouldn't freeze on second page/step on given URL
### Actual behavior

The countdown is seemingly frozen when out-of-focus.

### Your environment

* Environment name and version: (e.g. Chrome 59): Google Chrome 97.0.4692.99 (arm64)
* Any specific potentially conflicting software installed: (e.g. antiviruses, firewalls, traffic counters, cleaners) AdGuard VPN - not sure if it could conflict.

---

@BottledSoda commented on [Sat Feb 05 2022](https://github.com/AdguardTeam/AdguardForMac/issues/1036#issuecomment-1030405236)

> ### Customer ID

I didn't get one after I seemingly sent a bug report via the Support thing. in AdGuard for Mac)

**Comment by ameshkov** [comment]
Well, the user is not on Github anymore. Hopefully, the issue is resolved, let's close it as "cannot repro"

**Comment by PerfectSalad** [comment]
@stanislav-atr Did you have AdGuard Annoyances Filter enabled?

**Comment by slavaleleka** [comment]
@PerfectSalad AdGuard Annoyances Filter should be enabled or disabled? how does it affect?

**Comment by PerfectSalad** [comment]
> @PerfectSalad AdGuard Annoyances Filter should be enabled or disabled?

This depends on the desired outcome; I think`powerclicks.xyz` was added in AG Annoyance Filter to `#%#//scriptlet("set-constant, "blurred", "false")



> how does it affect?

If the issue was user-filter-only, the timer wouldn't freeze (unless the webmaster did something to the coutdown/`blurred` thing.

**Comment by stanislav-atr** [comment]
@PerfectSalad, hi! I've checked the issue again with the latest nightly version of AdGuard for Mac: constant is being set with scirptlet and timer goes on even if i focus on another element on the page or even switch tabs.

Domain was indeed added to #%#//scriptlet("set-constant, "blurred", "false") in Annoyance filter.
