### ISSUE TITLE
Improve `abort-on-stack-trace` — protect RegExp.test()

### ISSUE THREAD

**Issue by piquark6046** [AdguardTeam/Scriptlets#197]
Ad-Shield patches RegExp.prototype.test, which annoys `log-on-stack-trace` and `abort-on-stack-trace`.

<details>
<summary>Screenshots</summary>

![Screenshot](https://user-images.githubusercontent.com/98787049/155373025-3ee5b32b-48b0-465b-806e-6b2b086a0bab.png)
![Screenshot1](https://user-images.githubusercontent.com/98787049/155373052-52d1ed91-dbe5-48ff-99ef-2eb8acbf63fc.png)

</details>

### Original Report
https://github.com/uBlockOrigin/uBlock-issues/issues/1741

---

### Related Issue
https://github.com/AdguardTeam/AdGuardExtra/issues/294

**Comment by JobcenterTycoon** [comment]
@stanislav-atr `soft98.ir` does the same now. See https://github.com/uBlockOrigin/uBlock-issues/issues/1741#issuecomment-1230520335
