### ISSUE TITLE
Unable to abort document.write specified by onerror attribute

### ISSUE THREAD

**Issue by Yuki2718** [AdguardTeam/Scriptlets#203]
URL: `coin-free.com`
Issue: `coin-free.com#%#//scriptlet('abort-on-stack-trace', 'document.write', 'onerror')` or even `coin-free.com#%#//scriptlet("abort-on-property-read", "document.write")` can't block anti-adb. I think it's an issue as both of them works on uBO.
Chrome Extension 4.0.141 on Brave 1.36.119

**Comment by stanislav-atr** [comment]
@Yuki2718, hi! I've checked the scriptlets and they work fine on my side: gtag is blocked and no adb message is shown
```
||googletagmanager.com/gtag/*$domain=coin-free.com

#%#//scriptlet('abort-on-stack-trace', 'document.write', 'onerror')
#%#//scriptlet("abort-on-property-read", "document.write")
```
Could you please check it again?

**Comment by Yuki2718** [comment]
Sorry, it was my bad - I didn't realize I have to save User rules on Beta extension as they're automatically saved on stable.
