### ISSUE TITLE
Fix `set-constant` — loop reassignments

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/Scriptlets#205]
Steps to reproduce
1. Install AdGuard Extension Beta (version 4.0.159)
2. Add this rule:
```
interia.pl#%#//scriptlet("set-constant", "Inpl.Abd.onDetected", "noopFunc")
```
3. Go to - [https://www.interia.pl/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.interia.pl%2F)

Website is broken.

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/161484001-1397798c-b6f1-42b9-b936-908107a0e736.png)

</details>

Related to - https://github.com/AdguardTeam/AdguardFilters/issues/114521

**Comment by AdamWr** [comment]
By the way, it's rather new issue, because it doesn't occur with extension stable version 4.0.141 and with AdGuard for Windows version 7.9 nightly 19 (build 3875, CL 1.9.43).

**Comment by ameshkov** [comment]
"Cannot redefine" is a bad sign, may be related to the extension changes, not the scriptlets changes.

**Comment by stanislav-atr** [comment]
@ameshkov, reproducable with old extension version.

**Comment by stanislav-atr** [comment]
@AdamWr @ameshkov current fix prevents scriptlet from breaking the site if there is object self-assignment, but doesnt make it work if value is set with `configurable: false` like on interia.pl
