### ISSUE TITLE
"prevent-bab" breaks DDoS protection by Cloudflare

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/Scriptlets#21]
### Steps to reproduce

1. Add this rule to user filter:
`1337x.st,ftuforum.com#%#//scriptlet("prevent-bab")`
2. Go to https://1337x.st/ or https://ftuforum.com/

### Expected behavior
Website should works correctly.

### Actual behavior
Checking browser is broken.

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/29142494/58506250-24402200-818f-11e9-962c-fd5c609b8f1a.png)

</details>

**Comment by Alex-302** [comment]
reCAPTCHA is also affected.

**Comment by Alex-302** [comment]
Current JS rule from ubo:
https://github.com/AdguardTeam/AdguardFilters/blob/901b1d27d7daa7e05320c61e2c20238173f40030/EnglishFilter/sections/antiadblock.txt#L42
It does not cause these issues.

**Comment by krystian3w** [comment]
Also bugged in uBO, so maybe @grohill must fix also...

```
1337x.st,ftuforum.com##+js(bab-defuser.js)
```

**Comment by gorhill** [comment]
The issue is due to this [documented `eval` behavior](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/eval#Description):

> If you use the `eval` function *indirectly*, by invoking it via a reference other than `eval`, [as of ECMAScript 5](http://www.ecma-international.org/ecma-262/5.1/#sec-10.4.2) it works in the global scope rather than the local scope.

**Comment by slavaleleka** [comment]
prevent-bab can not be fixed, because it redefines eval in order to blockAdBlock circumventing, and that breaks DDoS protection by Cloudflare

so better not to use it for cases where it can break something. for example, abort-current-inline-script would be enough for inline bab scripts
