### ISSUE TITLE
Add a new scriptlet — `no-topics`

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/Scriptlets#214]
Check the document on how the topics are used and how they can be tested:
https://developer.chrome.com/docs/privacy-sandbox/topics/

Here's what we should do:
1. Add a new `no-topics` scriptlet (just like the `no-floc` scriptlet we had earlier).
2. Suppress JS API of the Chrome topics

**Comment by ghajini** [comment]
@gorhill
