### ISSUE TITLE
NanoResources: other possible scriptlets

### ISSUE THREAD

**Issue by superlex** [AdguardTeam/Scriptlets#22]
Hello,
check if they can be useful:
https://github.com/NanoAdblocker/NanoFilters/blob/master/NanoFiltersSource/NanoResources.txt
They are part of NanoAdblocker:
https://github.com/NanoAdblocker

Thanks.

**Comment by ameshkov** [comment]
These two are really good btw:
```
nano-tiny-noopvast-2.0 text/xml
<VAST version="2.0"></VAST>


nano-tiny-noopvast-3.0 text/xml
<VAST version="3.0"></VAST>
```

**Comment by slavaleleka** [comment]
both redirects are added:
- [noopvast-2.0](https://github.com/AdguardTeam/Scriptlets/blob/master/wiki/about-redirects.md#noopvast-2.0)
- [noopvast-3.0](https://github.com/AdguardTeam/Scriptlets/blob/master/wiki/about-redirects.md#noopvast-3.0)
