### ISSUE TITLE
Fix `abort-current-inline-script` — lost context

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/Scriptlets#248]
If I'm not wrong, [latest changes](https://github.com/AdguardTeam/Scriptlets/commit/d217c78b69c2871e0c3639d69258ce4affd0a595) caused that in some cases `abort-current-inline-script` might break website.

Steps to reproduce
1. Add this rule:
```adblock
w3schools.com#%#//scriptlet("abort-current-inline-script", "$", "TEST_TEST_TEST_TEST_TEST")
```
2. Go to - https://www.w3schools.com/jquery/trysel.asp
3. Click on any of the element (marked on a screenshot below)
<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/192098249-e1ce2067-110e-4898-b5c9-c20251306251.png)

</details>

Clicked element should be highlighted in the `Result` pane on the right, but scriptlet causes that it doesn't work.
```
Uncaught TypeError: $ is not a function
```

This issue probably occurs only with latest nightly build AdGuard for Windows (7.11 nightly 14 (build 4056, CL 1.10.94)).
I cannot reproduce it with extension AdGuard AdBlocker 4.1.22 (I suppose that latest scriptlets library is not used in extensions yet).

I guess that changing `return currentValue` to `return this.currentValue` here:
https://github.com/AdguardTeam/Scriptlets/blob/d217c78b69c2871e0c3639d69258ce4affd0a595/src/scriptlets/abort-current-inline-script.js#L165-L186
should fixes this issue.

**Comment by ameshkov** [comment]
Seems rather problematic, let's fix this before we release the new Win/Mac versions.
@maximtop

**Comment by AdamWr** [comment]
It seems that this issue also occurs with extension stable version 4.1.36 now.
So, I think that it would be nice to implement the patch to extensions and CoreLibs sooner rather than later :upside_down_face:
