### ISSUE TITLE
Add new scriptlets — 'xml-prune'

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/Scriptlets#249]
Related to this - https://github.com/AdguardTeam/Scriptlets/issues/202, but it shouldn't be a `trusted` scriptlet.
It could be useful in these cases:
https://github.com/AdguardTeam/AdguardFilters/commit/c2fc8a1b6f7ee237ec664333d4436e1719da99f8
https://github.com/AdguardTeam/AdguardFilters/commit/de413ca5ff4658c35a8c52efbed98e72a0c4c33f
https://github.com/AdguardTeam/AdGuardExtra/issues/297#issuecomment-1172894064

Similar scriptlet in uBlock Origin (I guess that it would be nice to make it compatible with it) - https://github.com/gorhill/uBlock/blob/ec83127f6c628bfa1ed2aeaf7f25873592d3a21f/assets/resources/scriptlets.js#L1672-L1739

**Comment by slavaleleka** [comment]
`m3u-prune` is not ready yet, will be released later
