### ISSUE TITLE
Decide what to do with these snippets

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/Scriptlets#25]
We can simply convert them to ExtCss rules, we should decide what to do with them:

* `hide-if-shadow-contains`
* `hide-if-contains-image`
* `hide-if-has-and-matches-style`
* `hide-if-contains-and-matches-style`
* `hide-if-contains`

**Comment by slavaleleka** [comment]
there are too few rules in ABP filters, so we won't  make AdGuard analogs for them
