### ISSUE TITLE
Fix `metrika-yandex-tag` — breaks login on id.x5.ru

### ISSUE THREAD

**Issue by zloyden** [AdguardTeam/Scriptlets#253]
https://github.com/AdguardTeam/AdguardFilters/issues/132855

---

Looks like that this redirect caused the problem.
I've added an exception to fix this, so you should use redirect rule with `$important` or disable the exception for checking this out.

**Comment by stanislav-atr** [comment]
This issue occurs because metrics tag.js script is patched and won't be fixed.

**Comment by rakleed** [comment]
@stanislav-atr please take a look: https://github.com/AdguardTeam/AdguardFilters/issues/137243
