### ISSUE TITLE
Improve storage item scriptlets — add regexp support for items removing

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/Scriptlets#256]
- add ability to remove a key
- add regex suppot for matching keys, which have variable part(for example `mp_***_mixpanel`, generated by Similarweb browser extension)

**Comment by slavaleleka** [comment]
for removing the key we may consider adding a new scriptlet

**Comment by Alex-302** [comment]
@slavaleleka Any news?)

**Comment by Alex-302** [comment]
@stanislav-atr Any news?)

**Comment by slavaleleka** [comment]
ability to remove an item from the storage is implemented already: https://github.com/AdguardTeam/Scriptlets/issues/338

but [there is no way to get all storage keys](https://developer.mozilla.org/en-US/docs/Web/API/Storage) so scriptlet shall not be able to match the needed ones by the regexp. it means that it's impossible to improve the current implementation and make regular expressions acceptable for storage items removing

**Comment by AdamWr** [comment]
Couldn't we use something like `Object.keys(localStorage)` and then iterate it to check if it contains a specific key which would be matched by regexp?

**Comment by slavaleleka** [comment]
you're right, we can try that
