### ISSUE TITLE
Fix `prevent-element-src-loading`

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/Scriptlets#264]
- [x] Fix issue with broken websites (I think that's the most important and I guess that other issues could be fixed later)

<hr>

- [ ] Fix issue with `onerror` (if I'm not wrong, it doesn't work correctly)
- [ ] Add ability to return `onload` function
- [ ] Add ability to prevent `link`

<hr>

Related issue - https://github.com/AdguardTeam/AdguardFilters/issues/136501

It looks like that scriptlet doesn't work correctly and it breaks website.
<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/205433811-d644edc7-924d-4f1d-bbca-8e6d00556fab.png)

</details>

> `Uncaught TypeError: thisArg.getAttribute is not a function`

As far as I understand, the problem is in this line:
https://github.com/AdguardTeam/Scriptlets/blob/202f6d855bdb576218b9fc9cabf4a54c82646360/src/scriptlets/prevent-element-src-loading.js#L173
`thisArg` sometimes doesn't have `getAttribute` method and it throws error.
So, I guess that checking if `getAttribute` is a function, for example, by something like this:
```js
thisArg.getAttribute?.(source.name)
```
should fixes this issue.

By the way, it looks like that this issue - https://github.com/AdguardTeam/Scriptlets/issues/228 is not fixed or I'm doing something wrong.
I have checked it here - https://jsfiddle.net/ofzmtek3/

<hr>

Additional notes.
It seems that it happens only with latest nightly build for Windows (7.12 nightly 1 (build 4121, CL 1.10.154)), because (if I'm not wrong) other versions do not use latest scriptlets library yet.

**Comment by AdamWr** [comment]
Two more things.

First - if I understand correctly, currently if there is `onerror` event then `noopFunc` is returned:
https://github.com/AdguardTeam/Scriptlets/blob/202f6d855bdb576218b9fc9cabf4a54c82646360/src/scriptlets/prevent-element-src-loading.js#L177

What in case if there will be `onload` event?
Something like:
```js
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js" onerror="showPopup();" onload="loadContent()"></script>

<script>
function showPopup() {
  alert('adblock');
}

function loadContent() {
 alert('content loaded');
}
</script>
```

Test website - https://jsfiddle.net/sL62htaz/
Will be `onload` executed or not?
If not, maybe it will be a good idea to check if `onload` is a function and then return it.

<hr>

Second - at the moment we can prevent `script`, `img` and `iframe`, but lately I noticed that one of the websites is using `link`.
Something like:
```js
<script>
(() => {
  const createScript = document.createElement("link");
  createScript.href = "https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js";
  createScript.rel = "preload";
  createScript.as = "script";

  createScript.onload = () => {
    let video = '<iframe width="560" height="315" src="https://www.youtube.com/embed/Fy2rtb95QhY" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>';
    let createDiv = document.createElement("div");
    document.body.appendChild(createDiv);
    createDiv.innerHTML = video;
  };
  createScript.onerror = () => {
    alert("adblock");
  };
  document.body.appendChild(createScript);
})();
</script>
```
Test page - https://jsfiddle.net/e2un8pav/

Maybe we could also add `link` to possible values.

**Comment by slavaleleka** [comment]
yes, only incorrect blocking is fixed. the issue should be opened due to other tasks. so better to create separate issues for different problems in future
