### ISSUE TITLE
prevent-window-open with specific parameters is not working 

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/Scriptlets#28]
Example:
https://www.stratege.ru/#args:ajax=1
```
<script type="text/javascript">$("#kkJ4fwMnl09_25706614").click(function() {window.open('https://ad.adriver.ru/cgi-bin/click.cgi?sid=1&ad=682279&bt=21&pid=2904284&bid=6153049&bn=6153049&rnd=1559918541', '_blank');});</script>
```

Works:
`#%#//scriptlet("prevent-window-open")`

Not works:
```
#%#//scriptlet("prevent-window-open", 0, "example")
```
```
#%#//scriptlet("prevent-window-open", 'Match', 'adriver')
```
```
#%#//scriptlet("prevent-window-open", 1, "/adriver\./")
```

Check with exclusion:
`stratege.ru#@%#//scriptlet("abort-current-inline-script", "window.open")`

**Comment by timirila1** [comment]
@Alex-302 
Description for this scriptlet is not correct.

Here is the updated description. It will appear in the next release.

------
### prevent-window-open
Prevents `window.open` calls when URL either matches or not matches the specified string/regexp. Using it without parameters prevents all `window.open` calls.

**Syntax**
```
example.org#%#//scriptlet("prevent-window-open"[, <match>[, <search>]])
```

**Parameters**
- `match` (optional) defaults to "matching", any positive number for "matching", 0 or any string for "not matching",
- `search` (optional) string or regexp for matching the URL passed to `window.open` call.

**Example**

1. Prevent all `window.open` calls:
    ```
    example.org#%#//scriptlet("prevent-window-open")
    ```

2. Prevent `window.open` for all URLs containing `example`:
    ```
    example.org#%#//scriptlet("prevent-window-open", "1", "example")
    ```

3. Prevent `window.open` for all URLs matching RegExp `/example\./`:
    ```
    example.org#%#//scriptlet("prevent-window-open", "1", "/example\./")
    ```

4. Prevent `window.open` for all URLs **NOT** containing `example`:
    ```
    example.org#%#//scriptlet("prevent-window-open", "0", "example")
    ```
