### ISSUE TITLE
Improve 'set-attr' scriptlet — add more possible values

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/Scriptlets#283]
https://github.com/AdguardTeam/Scriptlets/blob/master/wiki/about-scriptlets.md#-%EF%B8%8F-set-attr
Allow to use 
`true`, `True`
`false`, `False`

Using of numbers only, makes this scritplet useless.

**Comment by krystian3w** [comment]
Maybe also should be moved to CSS or pseudo-class syntax:

```adb
example.org##div:set-attr(foo, bar)
example.org#$#div { set-attr: "foo, bar" }
```
