### ISSUE TITLE
Text-based removement scriptlet

### ISSUE THREAD

**Issue by BlazDT** [AdguardTeam/Scriptlets#29]
Would be good to have a scriptlet which removes a specific text out of a div id for example.

Example:
https://www.file-up.org/yzamat3xs0i7

The "ads" text there is not in a seperate DOM element, so currently javascript has to be removed to remove them, e. g.:

`file-up.org#%#AG_onLoad(function() { setTimeout(function() { var el = document.getElementsByClassName('page-wrap')[0]; if(el) {el.innerHTML = el.innerHTML.replace('ads',''); el.innerHTML = el.innerHTML.replace('ads',''); el.innerHTML = el.innerHTML.replace('ads',''); } }, 300); });`

**Comment by ameshkov** [comment]
This can be handled by using an XPath.

So I guess we should extend our cosmetic rules and add xpath support to ExtendedCss module instead.
