### ISSUE TITLE
'prevent-xhr' or 'prevent-fetch' does not work well in Apple Safari

### ISSUE THREAD

**Issue by piquark6046** [AdguardTeam/Scriptlets#290]
### Expected behavior
The following scriptlets executed in the time:
```adblock
tv.kakao.com,play-tv.kakao.com,kakaotv.daum.net#%#//scriptlet('prevent-fetch', '/^https.\/\/videoads\.kakao\.com\/adserver\/api\/v[0-9]{1,2}\/vmap$/')
tv.kakao.com,play-tv.kakao.com,kakaotv.daum.net#%#//scriptlet('prevent-xhr', '/^https.\/\/videoads\.kakao\.com\/adserver\/api\/v[0-9]{1,2}\/vmap$/')
```

### Actual behavior
> It seems the rules which block `/vmap` can't work or scriptlets executed not in time in Safari.

https://github.com/AdguardTeam/AdguardFilters/issues/142468#issuecomment-1425572770

### Note
https://github.com/AdguardTeam/AdguardFilters/issues/142468

**Comment by stanislav-atr** [comment]
I wasn't able to reproduce this, as request `https://videoads.kakao.com/adserver/api/v1/vmap` is absent in safari on these pages
https://tv.kakao.com/channel/3861791/cliplink/438102581
https://sports.daum.net/video/435684541 в сафари
with both eu and korean IPs
