### ISSUE TITLE
Can't redefine 'window.location'

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/Scriptlets#309]
**Site [porn]**  `https://www.jpvhub.com/download?link=streamtape.com/v/ZDykQMqbRYsyYl`
**Script**

```
r.a.createElement(o, null), r.a.createElement("a", {
                className: "".concat(n.text_container),
                onClick: function() {
                    window.open("http://".concat(i), "_blank"), window.location = "https://remorsefulindependence.com/bR3/Vv0hP.3dpQvCbMmXVLJ-ZMDD0N0QN/DKQk1/NEznks5/L/TPQq0SNOD-Uw4dMiDLAd"
                }
            },
```

`window.open` should not be broken (it opens a new tab, where a video can be downloaded), only `window.location` used for ad redirect.

`jpvhub.com#%#//scriptlet('set-constant', 'location', 'undefined')` does not redefine `window.location`

**Comment by AdamWr** [comment]
According to https://developer.mozilla.org/en-US/docs/Web/API/Window/location `window.location` is read-only, so it's probably a reason why it cannot be redefined.
I guess that in this case the easiest solution would be to automatically redirect to destination page, as it's part of the link.

**Comment by Alex-302** [comment]
Shouldn't the scriptlet throw an error in this case?

**Comment by AdamWr** [comment]
As far as I understand, it should shows message in browser console:
https://github.com/AdguardTeam/Scriptlets/blob/091247665fb9e83d68fb16d63c5246fff70fb7c3/src/scriptlets/set-constant.js#L184-L187
but it doesn't.
Probably changing `logMessage(source, message);` to `logMessage(source, message, true);` should fixes it.

**Comment by AdamWr** [comment]
Or maybe I'm wrong and this message should be only displayed when filtering log is enabled.
At least it seems that currently it works like that.

**Comment by slavaleleka** [comment]
yes, that message is logged in debug mode (which can be enabled by filtering log opening)

**Comment by maximtop** [comment]
It's impossible to redefine window.location
