### ISSUE TITLE
Fix cookie setting scriptlets — do not encode name and value

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/Scriptlets#311]
Examples:
* `karofilm.ru#%#//scriptlet('trusted-set-cookie-reload', 'pop::138', '138')`

<details>
<summary>Details</summary>

![image](https://user-images.githubusercontent.com/8361299/232312687-802e9f68-a602-4cc0-a277-d825fda135e1.png)

</details>

* `#%#//scriptlet('trusted-set-cookie', '__w_cc11', '{%22preferences%22:false%2C%22analysis%22:false%2C%22marketing%22:false}')`

<details>
<summary>Details (second line)</summary>

![image](https://user-images.githubusercontent.com/8361299/232312721-a9b17147-9f42-45b0-8aef-affe5a659fbb.png)

</details>

**Comment by slavaleleka** [comment]
cookie name and value shall not be encoded by `trusted-set-cookie` and `trusted-set-cookie-reload`
