### ISSUE TITLE
'prevent-setTimeout' does not work in logging mode

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/Scriptlets#312]
AdGuard for Chrome 4.1.55
AdGuard for Windows 7.13 n9

Address: `https://math-oge.sdamgia.ru/`
Rule: `sdamgia.ru#%#//scriptlet("prevent-setTimeout")`

<details>
<summary>Details</summary>

![image](https://user-images.githubusercontent.com/8361299/234391637-24bcc223-1de5-417e-841c-51deff2bc52b.png)

</details>

**Comment by maximtop** [comment]
looks like it works on my side
message should be fixed, but in general, the content of the setTimeout is visible
<img width="1120" alt="image" src="https://user-images.githubusercontent.com/17272769/234591085-68875d8e-ce68-4b12-8545-a858c7ad4034.png">

**Comment by maximtop** [comment]
looks like it works on my side
the message should be fixed, but in general, the content of the setTimeout is visible

<img width="1724" alt="image" src="https://user-images.githubusercontent.com/17272769/234592096-ea0aacbc-0e1d-47b8-b58d-dd3ee71f7cdf.png">
