### ISSUE TITLE
Add new scriptlet — 'remove-node-text'

### ISSUE THREAD

**Issue by Yuki2718** [AdguardTeam/Scriptlets#318]
https://github.com/gorhill/uBlock/commit/2bb446797a12086f2eebc0c8635b671b8b90c477
It's not a trusted scriptlet. We already have several rules to remove node text, e.g. in Japanese filters
```
jisakuhibi.jp#%#AG_onLoad(function() { var el = document.querySelector('.article-body'); if(el) { el.innerHTML = el.innerHTML.replace(/スポンサードリンク/g,''); } });
rank1-media.com#%#AG_onLoad(function() { document.body.innerHTML = document.body.innerHTML.replace(/スポンサードリンク/g, ""); });
2ch.pet#%#AG_onLoad(function() { document.body.innerHTML = document.body.innerHTML.replace(/広告/g, ""); });
```
It will be nice to have the scriptlet and replace these rules with it, also for similar cases in future.

**Comment by ameshkov** [comment]
Good idea!

**Comment by Alex-302** [comment]
@ameshkov Maybe better **[replace](https://github.com/gorhill/uBlock/blob/master/assets/resources/scriptlets.js#L2437)** ?

**Comment by Yuki2718** [comment]
> Maybe better **[replace](https://github.com/gorhill/uBlock/blob/master/assets/resources/scriptlets.js#L2437)** ?

uBO first introduced that which is a trusted scriptlet. The point of `remove-node-text` is it's not trusted one.

**Comment by Alex-302** [comment]
Common version can be made from a more powerful.

**Comment by Yuki2718** [comment]
Ah, actually not all of them can be removed by `remove-node-text` as it removes all texts. Some requires replace-node-text.
