### ISSUE TITLE
Value encoding problem with 'trusted-set-cookie' and 'trusted-set-cookie-reload' scriptlets

### ISSUE THREAD

**Issue by zloyden** [AdguardTeam/Scriptlets#320]
https://github.com/AdguardTeam/AdguardFilters/issues/152360.
There is a problem with this scriptlet. It adds a wrong value.
```adblock
matkahuolto.fi#%#//scriptlet('trusted-set-cookie', 'CookieConsentV2', 'YES%2CTOI%2CANA%2CKOH')
```

<details><summary>Screenshot:</summary>

![image](https://github.com/AdguardTeam/Scriptlets/assets/33488229/4af79a36-65b9-472b-894f-73096bf11897)
</details><br/>

The expected behavior is shown in the screenshot below.
<details><summary>the correct value:</summary>

![image](https://github.com/AdguardTeam/Scriptlets/assets/33488229/7086f20c-f49f-491a-9461-652d47497bc9)

</details><br/>

**Comment by slavaleleka** [comment]
related to https://github.com/AdguardTeam/Scriptlets/issues/311, the fix will be available in the upcoming scriptlets release
