### ISSUE TITLE
Improve 'trusted-click-element' — add support for finding selectors in shadowRoot

### ISSUE THREAD

**Issue by zloyden** [AdguardTeam/Scriptlets#323]
According to https://github.com/AdguardTeam/AdguardFilters/pull/152438, it would be nice if the our `trusted-click-element` could match selectors in shadowRoot(open). I did not find [the information](https://github.com/AdguardTeam/Scriptlets/blob/master/wiki/about-trusted-scriptlets.md?rgh-link-date=2023-05-31T10%3A32%3A31Z#-%EF%B8%8F-trusted-click-element) about this here.
If it is not possible to do it in the current scriptlet, how about creating another one `trusted-click-element-in-shadow-dom`?

**Comment by krystian3w** [comment]
Possible: https://github.com/gorhill/uBlock/commit/941077a25ccd233d435398246312d3b388493d5a So if it doesn't work without diffrent name we have a bug in the AdGuard library.
