### ISSUE TITLE
Fix 'remove-cookie' — broken kupi.cz

### ISSUE THREAD

**Issue by zloyden** [AdguardTeam/Scriptlets#326]
https://github.com/AdguardTeam/AdguardFilters/issues/153225.
Seems like a bug in our extension, which is caused by `kupi.cz#%#//scriptlet('ubo-cookie-remover.js', '/^_?adb/')`. I can't reproduce it in uBO.

**Comment by AdamWr** [comment]
As I recall, it's some kind of ad reinjection script and after refreshing website few times I can reproduce it with uBO as well.

<details><summary>Screenshot</summary>

![image](https://github.com/AdguardTeam/Scriptlets/assets/29142494/45830525-6c28-44bf-8bae-6c4f66272fd4)

</details>

It looks like that if `adb` cookie is removed by scriptlet, then some scripts do not load for some reason, but I'm not sure if it's a scriptlet issue.

<details><summary>Screenshot</summary>

![image](https://github.com/AdguardTeam/Scriptlets/assets/29142494/07f98cc0-b92f-4733-a655-a17ade7a38fe)

</details>

It seems that if `adb` cookie is removed before reloading a website, then it also works correctly, so maybe this part:
https://github.com/AdguardTeam/Scriptlets/blob/323fd41e0f2e3eb540555f2b182d0aefd1874db0/src/scriptlets/remove-cookie.js#L89
doesn't work correctly in this case.
