### ISSUE TITLE
Add new scriptlet — 'call-nothrow.js'

### ISSUE THREAD

**Issue by piquark6046** [AdguardTeam/Scriptlets#333]
- https://github.com/gorhill/uBlock/commit/e93117cbb607472a830e1c0653dfbddde4c965fc

**Comment by piquark6046** [comment]
https://listauthorschat.slack.com/archives/C010N14G4TF/p1691108059784199?thread_ts=1683754186.016929&cid=C010N14G4TF
Now, this issue is related to YouTube anti-adblock.

**Comment by ovvldc** [comment]
Never mind, I got it to work with a couple of additional filters...

Perhaps you could write a blog post on which filters to turn on to avoid this kind of ad enforcement?
