### ISSUE TITLE
hyperlink

### ISSUE THREAD

**Issue by bogachenko** [AdguardTeam/Scriptlets#34]
Check out this case `https://github.com/AdguardTeam/AdguardFilters/issues/35520` and please add this scriptlet `https://github.com/uBlock-user/uBO-Scriptlets/blob/5dc749eea188960eaaa1c75d2eca463e361bcdf3/scriptlets.txt#L67`

PS: Will there be support for my scriptlets so that I can add ~not~ my scriptlets without typing messages here, such as subscriptions?

**Comment by ameshkov** [comment]
> PS: Will there be support for my scriptlets so that I can add not my scriptlets without typing messages here, such as subscriptions?

We have not decided on this yet

**Comment by bogachenko** [comment]
>We have not decided on this yet

Ну вы чего, годная же функция.


***
2 оффтопика. 
1) а зачем вы листы с подписками в расширением пихаете?
этож геморой не все выбирают ваши дефолтные подписки + большой размер, не легче этого не делать?

2) _у меня есть мой личный список фильтров, там есть всяко разные скриптлеты, которые я спер у анимебоя (помошника горхилла) и которых  нет в AG. для например см пик ниже_

![ыыыыыыыыы](https://user-images.githubusercontent.com/8535285/63389949-2c5bd680-c3f9-11e9-970e-ad96dbc4e960.png)

Возвращаясь к https://github.com/AdguardTeam/AdguardBrowserExtension/issues/1353#issuecomment-477985703 вы сделали круто, однако как на счет сделать отличая цветов, какие выполнены, а какие нет. Любой нейтральный цвет подойдет.

**Comment by ameshkov** [comment]
@bogachenko 

Так, сорян за задержку, лучше поздно чем никогда:)

> Ну вы чего, годная же функция.

Ну просто для этого есть JS-правила где вообще чего хочешь то и пиши. Мы их юзер фильтром ограничим.

> а зачем вы листы с подписками в расширением пихаете?

Ну цель чтобы даже при офлайн-установке расширение рабочим было.

> однако забыли пометить, как на счет сделать отличая цветов, какие выполнены, а какие нет (которые просто отображаются). Любой нейтральный цвет подойдет.

Да просто придержали пока, сложно достаточно пробрасывать обратно в расширение эту информацию, может быть еще одним способом детектить наличие расширение.

> почему при открытии настроек в моде "Приватное окно" , окно открывается не в приватном окне, аналогично с логгером (если копировать url и вставлять в urlbar)

А это потому что мы не делим расширение и его настройки между приватным и обычным режимом.

**Comment by bogachenko** [comment]
@ameshkov 
>Ну просто для этого есть JS-правила где вообще чего хочешь то и пиши. Мы их юзер фильтром ограничим.

я не знаю JS (чтобы написать полноценный скрипт), но я знаю, как применять правильно скриптлеты.

>А это потому что мы не делим расширение и его настройки между приватным и обычным режимом.

И Окей зачем вы это делаете, я работаю только в приватном режиме (по умолчанию поставил в фирефокс), и открытие нового окна не удобно.
PS. логгер всегда открываю в новой вкладке, копирую URL и вставляю, но в опере даже при копировании и вставке в приватное окно происходит - ничего. Открывается новое не приватное окно и каждый раз скакание из приватного в не приватное  - геморрой.

**Comment by ameshkov** [comment]
> Окей и зачем вы это делаете, я работаю только в приватном режиме (по умолчанию поставил в фирефокс), и открытие нового окна не удобно.

Хм, интересный вариант. Завел задачку, посмотрим что получится: https://github.com/AdguardTeam/AdguardBrowserExtension/issues/1495

**Comment by ameshkov** [comment]
@slavaleleka regarding this issue, I am okay if make a website-specific scriptlet (just like prevent-bab and all this kind of scriptlets).

**Comment by ameshkov** [comment]
Issue moved to [AdguardTeam/AdGuardExtra #94](https://github.com/AdguardTeam/AdGuardExtra/issues/94) via [**ZenHub**](https://www.zenhub.com/)

**Comment by bogachenko** [comment]
@ameshkov еще бы это добавить, куча сайтов использует такой метод, паршивый яндекс например
https://github.com/uBlock-user/uBO-Scriptlets/blob/master/scriptlets.js#L3
```js
/// remove-shadowroot-elem.js
/// alias rsre.js
// example.com##+js(rsre, [selector])
(() => {
		'use strict';
		const selector = '{{1}}';
		if ( selector === '' || selector === '{{1}}' ) { return; }
		let asyncTimer;
		const queryShadowRootElement = (shadowRootElement, rootElement) => {
	      		if (!rootElement) {
        		     return queryShadowRootElement(shadowRootElement, document.documentElement);
           		}
   			const els = rootElement.querySelectorAll(shadowRootElement);
    			for (const el of els) { if (el) {return el;} }
    			const probes = rootElement.querySelectorAll('*');
    			for (const probe of probes) {
        		     if (probe.shadowRoot) {
            			 const shadowElement = queryShadowRootElement(shadowRootElement, probe.shadowRoot);
            			 if (shadowElement) { return shadowElement; }
        		     }
    			}
    			return null;
		};
		const rmshadowelem = () => {
					   	asyncTimer = undefined;
						try {
						  	const elem = queryShadowRootElement(selector);
						  	if (elem) { elem.remove(); }
					   	} catch { }
		};
		const rmshadowelemAsync = () => {
						   if ( asyncTimer !== undefined ) { return; }
						   asyncTimer = window.requestAnimationFrame(rmshadowelem);
		};	
		const observer = new MutationObserver(rmshadowelemAsync);
    		observer.observe(document.documentElement, { childList: true, subtree: true });
		if ( document.readyState === "complete" ) { observer.disconnect(); }
})();
```

**Comment by ameshkov** [comment]
Да, сделаем.

У нас кстати более модный есть: https://github.com/AdguardTeam/Scriptlets/blob/master/wiki/about-scriptlets.md#hide-in-shadow-dom

**Comment by ameshkov** [comment]
@bogachenko а еще обрати внимание, что он только открытые шадоу руты ищет так что с яндексом это никак не поможет.

Их можно "открыть" насильно переопределив Element.prototype.attachShadow + переопределив createElement и отлавливая создание фреймов (яндекс может оттуда тащить имплементацию attachShadow), но это уже сложнее

**Comment by bogachenko** [comment]
Ну я с яндексом не проверял, неделю назад на яндекс погоде шадоу рут видел, вот и запомнил. А сегодня с утра у анимешника этот скрипт нашел.
