### ISSUE TITLE
thisArg.collectedHeaders is undefined

### ISSUE THREAD

**Issue by piquark6046** [AdguardTeam/Scriptlets#349]
After `aagag.com#%#//scriptlet('prevent-xhr', 'pagead2.googlesyndication.com/pagead/js/adsbygoogle.js')` in AdGuard Browser Extension on Firefox, an `Uncaught TypeError: can't access property "length", thisArg.collectedHeaders is undefined` error is raised.

https://github.com/AdguardTeam/Scriptlets/blob/5c1ccffb7a7dc175c46a514458949ec9bb8b8d11/src/scriptlets/prevent-xhr.js#L248-L262

Instead of simply using logical not operator (`!`), please use `typeof` operator to test before it.

### Environment
 - Operating System: Ubuntu 23.04
 - Browser: Mozilla Firefox Developer Edition 117.0b2
 - AdGuard Browser Extension version: 4.2.142
 - URL: https://aagag.com/issue/?idx=1267082

**Comment by piquark6046** [comment]
AdGuard Browser Extension 4.1.57 on Firefox is not affected.

**Comment by AdamWr** [comment]
I suppose that it might be the same issue as here - https://github.com/AdguardTeam/Scriptlets/issues/347#issuecomment-1660345912

**Comment by piquark6046** [comment]
I think that this issue has to be prioritized to a upper class because this issue causes breakages if `prevent-xhr`  scriptlet is applied in a webpage.
Confirmed a website having this issue:
 - https://laftel.net
 - https://github.com/AdguardTeam/AdguardFilters/issues/158932

**Comment by AdamWr** [comment]
It should be already fixed in scriptlets library version 1.9.62.
