### ISSUE TITLE
'trusted-click-element' does not work on kicker.de in AdGuard Extension 4.2.151

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/Scriptlets#352]
**URL**: https://www.kicker.de/kicker-tv/videos#
**Rule**: 

`kicker.de#%#//scriptlet('trusted-click-element', '#kick__logi-container a[onclick="ov.cmp.acceptAllConsents()"]')`

or

`kicker.de#%#//scriptlet('trusted-click-element', '#kick__logi-container a[onclick="ov.cmp.acceptAllConsents()"]', '', '2500')`

**Element to click**:

`Zustimmen & weiter`

<details>
<summary>Details</summary>

![image](https://github.com/AdguardTeam/Scriptlets/assets/8361299/49b74cd3-8d12-4150-81e7-ea985d05ed41)

</details>

**Browse**: Chrome 114

**Steps to reproduce**:

1. Disable all filters
2. Add one of the rules above to user rules
3. Open the link (`Clear site data` after each refresh)

**Expected behavior**:
Scriptlet clicks the button, than player loads.

**Actual behavior**:

Scriptlet does not work at all on this site, when used AdGuard Extension for Chrome.

**Comment by AdamWr** [comment]
If I'm not wrong, the problem is that button is clicked "too fast" and required script (`https://app.usercentrics.eu/browser-ui/3.26.0/index.module.js`) is not loaded yet.
<details><summary>Screenshot</summary>

![image](https://github.com/AdguardTeam/Scriptlets/assets/29142494/596f6751-affb-43c3-bcd6-ce3c47455314)

</details>

This rule:
```adblock
kicker.de#%#//scriptlet('trusted-click-element', '#kick__pur__layer[style="display: block;"] #kick__logi-container a[onclick="ov.cmp.acceptAllConsents()"]')
```
seems to be working correctly.

**Comment by Alex-302** [comment]
Ok, replaced https://github.com/AdguardTeam/AdguardFilters/commit/201a0c05a109214eb69aa56171c4e3b069f780d5

I just tried to click very fast, and it worked, but with the scriptled a delay was required if did not used your selector.
