### ISSUE TITLE
Increase length of `googlesyndication-adsbygoogle` redirection resoruce

### ISSUE THREAD

**Issue by piquark6046** [AdguardTeam/Scriptlets#357]
### Expected and Actual Behaviors

![image](https://github.com/AdguardTeam/Scriptlets/assets/98787049/8977778c-edcf-43f0-84de-e0fa69dfa763)

The anti-adblock script on aagag.com checks factors mentioned in #350 and its length.

### Environment 
- Operating System: Ubuntu 23.04
- Web Browser: Mozilla Firefox Developer Edition 118.0b6
- AdGuard product: AdGuard Browser extension 4.2.168

### Additional Information

- https://piquark6046.github.io/testpage/XMLResponse-aagag/20230908/
- https://github.com/AdguardTeam/AdguardFilters/issues/161141
- https://github.com/List-KR/List-KR/issues/769#issuecomment-1711403255

**Comment by ameshkov** [comment]
If they want to detect that they're dealing with a stub, they will be able to do that, script size is just one of the factors, we cannot remove all of these signals.
