### ISSUE TITLE
Add uBlock Origin conversion for trusted- scriptlets

### ISSUE THREAD

**Issue by superlex** [AdguardTeam/Scriptlets#363]
Hi guys,
it looks like trusted- scriptlets are not converted from uBlock syntax to yours.

`example.org##+js(trusted-set-local-storage-item, example, ex)`
should match with
`example.org#%#//scriptlet('trusted-set-local-storage-item', 'example', 'ex')`

`example.org##+js(trusted-set-cookie, example, ex)`
should match with
`example.org#%#//scriptlet('trusted-set-cookie', 'example', 'ex')`

Currently, only set-cookie and set-local-storage-item match.

I'm using AG ext for Firefox, v. 4.2.168

**Comment by slavaleleka** [comment]
trusted scriptlets are designed to have to aliases, e.i. they are not compatible with any other blocker
https://github.com/AdguardTeam/Scriptlets#trusted-scriptlets

**Comment by slavaleleka** [comment]
adding any filter list as custom and having potentially dangerous rules in "pre-installed" filter lists is not the same

**Comment by superlex** [comment]
Oh ok!
Thanks anyway!

**Comment by krystian3w** [comment]
Someone can create PR-s between projects - e.g. bot or AI to fix ads/detections/trackers/annoyances with fail fix by other ideas.

**Comment by superlex** [comment]
Btw, uBlock0 supports both of syntaxes:

<img width="1155" alt="uBlock0" src="https://github.com/AdguardTeam/Scriptlets/assets/1375223/2898d2f7-92e7-4a88-af7a-d2b03671e076">
