### ISSUE TITLE
Add new trusted scriptlet — trusted-prune-inbound-object

### ISSUE THREAD

**Issue by Yuki2718** [AdguardTeam/Scriptlets#372]
Inspired by @AdamWr 's idea shared on Slack, uBO added [this](https://github.com/gorhill/uBlock/commit/1c9da227d7) scriptlet.

**Comment by Yuki2718** [comment]
It seems not this is countered, this issue can be set to low priority, or can be closed. cc: @AdamWr

**Comment by AdamWr** [comment]
I didn't check uBO solution, but the JavaScript rule from Slack still works on my end if add `json-prune` scriptlet.
