### ISSUE TITLE
Improve set-cookie — add more supported values

### ISSUE THREAD

**Issue by peace2000** [AdguardTeam/Scriptlets#375]
More values were added to uBO as accepted values https://github.com/gorhill/uBlock/commit/d51b393fdbdc7dec0e21086795b9ce394cf21adf. Can you add them to AG as well?

Added values were:
`rejected`
`allowed`
`disallow`
`accepted`
`notaccepted`
`enable`
`enabled`
`disable`
`disabled`

**Comment by slavaleleka** [comment]
### support "on" and "off"

Used on `praxisplan.at`.

https://github.com/uBlockOrigin/uAssets/commit/0cd4612e1815afa8b0225d2853220fec0280874a

(Also made a proposal to add them to uBO as well)

> originally reported in https://github.com/AdguardTeam/Scriptlets/issues/366
