### ISSUE TITLE
Add missing redirect resources

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/Scriptlets#38]
Here is the list:

* googlesyndication.com/adsbygoogle.js
* googletagmanager.com/gtm.js
* google-analytics.com/analytics.js
* google-analytics.com/ga.js
* googletagservices.com/gpt.js
* scorecardresearch.com/beacon.js

**Comment by timirila1** [comment]
- [x] googlesyndication.com/adsbygoogle.js
- [x] googletagmanager.com/gtm.js
- [x] google-analytics.com/analytics.js
- [ ] google-analytics.com/ga.js
- [ ] googletagservices.com/gpt.js
- [x] scorecardresearch.com/beacon.js
