### ISSUE TITLE
Add new scriptlet — 'trusted-suppress-native-method'

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/Scriptlets#383]
[Example](https://www.inxxx.com/v/big-dick-christy-mack-fucks-one-lucky-photographer-cowgirl-video.xxx-video), where it may be useful - site checks `_egoTab` key and it's value. 
Actually more sites like this, since we can block in other ways. But this method can speed up rule creation.

* @AdamWr 's JS rule for this purpose works on https://www.baeldung.com/kotlin/let-vs-if-not-null
	`#%#!function(){const e={apply:(e,o,t)=>{if(t[0]&&t[0].includes("fs.adb"))throw new Error;return Reflect.apply(e,o,t)}};window.localStorage.setItem=new Proxy(window.localStorage.setItem,e)}();`

**Comment by AdamWr** [comment]
What do you think about making it a more generic scriptlet?
I mean that instead of just `localStorage` it could be any property (similar like it's done in `trusted-prune-inbound-object` scriptlet) and if it would contains specific argument, then it could be aborted.

**Comment by Alex-302** [comment]
@AdamWr Maybe it is a good idea, but in this case it could be used only in our (trusted) filters.

**Comment by ameshkov** [comment]
I actually think that "abort" scriptlets are relatively safe and we can make it generally available
