### ISSUE TITLE
`xml-prune` does not work on serially.it

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/Scriptlets#398]
AdGuard syntax - doesn't work in AdGuard
`serially.it#%#//scriptlet('xml-prune', 'xpath(//*[name()="Period"][.//*[name()="BaseURL" and contains(text()\,"/ad/")]])', '', '.mpd')`

Ublock syntax - works in uBO
`serially.it##+js(xml-prune, xpath(//*[name()="Period"][.//*[name()="BaseURL" and contains(text()\,'/ad/')]]), , .mpd)`

Checked in Chrome.
AdGuard 4.2.241
URL: https://www.serially.it/play/b2d953bc-b9df-4bed-a7b1-e3436be8bbdd_AEBE0Fc?t=0

Need Italian IP. The moment when to watch advertising can be determined by the marks on the progress bar, then with the ad blocker rewind to ad time minus a few seconds.

**Comment by AdamWr** [comment]
It seems that it works correctly if `,` in `text()\,"` is not escaped:
```adblock
serially.it#%#//scriptlet('xml-prune', 'xpath(//*[name()="Period"][.//*[name()="BaseURL" and contains(text(),"/ad/")]])', '', '.mpd')
```

**Comment by Alex-302** [comment]
Yep. Thanks.
