### ISSUE TITLE
Fix 'noopjs' — breakage on vseinstrumenti.ru

### ISSUE THREAD

**Issue by zloyden** [AdguardTeam/Scriptlets#406]
For some reason, after applying the rule `||yandex.ru/ads/system/context.js$script,xmlhttprequest,redirect-rule=noopjs` on `vseinstrumenti.ru` a useful element is gone.
<details><summary>Screenshot:</summary>

![image](https://github.com/AdguardTeam/Scriptlets/assets/33488229/c74adf97-b1d4-4508-9048-b2e29d74ccb4)

</details><br/>
For now it's fixed by excluding the domain from the rule. Let me know if there will be a fix in this case or not.

---

Expected behavior.
<details><summary>Screenshot:</summary>

![image](https://github.com/AdguardTeam/Scriptlets/assets/33488229/105c66fa-3f55-4136-b3f1-0ad7a3aeb92a)

</details><br/>

---

STR:
1. Turn only the AdGuard Base on
2. Add the rule below
```adblock
||yandex.ru/ads/system/context.js$script,xmlhttprequest,redirect-rule=noopjs
```
3. Open `vseinstrumenti.ru`.

**Comment by jellizaveta** [comment]
Unfortunately, I wasn't able to reproduce this issue. The site design has changed, other blocks are not hidden with redirect.
