### ISSUE TITLE
Improve 'abort-current-inline-script'

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/Scriptlets#42]
Improve `abort-current-inline-script` to avoid preventing it by some scripts.

https://github.com/JamesMGreene/document.currentScript

**Comment by ameshkov** [comment]
@timirila1 the problem is that on some websites they're doing this:
```
(function () {
  try {
    Object.defineProperty(document.currentScript, "textContent", {
      get: function get() {
        return "";
      }
    });
  } catch (err) {}
alert("test");
})();
```

**Comment by ameshkov** [comment]
Fixed by https://github.com/AdguardTeam/Scriptlets/commit/177e9da7e275e8bee84e5d270ca9980dcd898d0d
