### ISSUE TITLE
Add new scriptlets — 'trusted-set-attr'

### ISSUE THREAD

**Issue by scripthunter7** [AdguardTeam/Scriptlets#431]
The `trusted-set-attr` scriptlet could change any attribute of any element:
```
example.com#%#//scriptlet('trusted-set-attr', selector, attr[, value])
```
where value can be anything

**Comment by AdamWr** [comment]
Maybe I misunderstand something, but don't we have already this scriptlet? - https://github.com/AdguardTeam/Scriptlets/blob/master/wiki/about-trusted-scriptlets.md#-%EF%B8%8F-trusted-set-attr
