### ISSUE TITLE
Implement json-prune.js scriptlet

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/Scriptlets#45]
Link
[uBO code](https://github.com/gorhill/uBlock/commit/2fd86a66fcc2665e5672cc5862e24b3782ee7504#diff-d7616deaf3a39e3f19f8d70d098bfe7a)

**Comment by AdamWr** [comment]
I'm not sure, but it seems that `json-prune` doesn't work correctly at the moment.
For example:
`adguard.com#%#//scriptlet("json-prune", "ThisIsTest.test123")`
causes errors.

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/71536444-a8b67700-290f-11ea-855f-35c6569fb36d.png)

</details>

Link - https://adguard.com/pl/welcome.html

**Comment by ameshkov** [comment]
Moved back to "In progress"

**Comment by Alex-302** [comment]
Not working at https://www.tv2.no/v/1549936/
`tv2.no#%#//scriptlet("json-prune", "enabled", "testhide")` (uBO syntax: `tv2.no##+js(json-prune, enabled, testhide)`)

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/8361299/76799585-7b74b900-67da-11ea-9786-84d4bbbacf76.png)

</details>
