### ISSUE TITLE
Tests failing for `trusted-set-cookie`

### ISSUE THREAD

**Issue by scripthunter7** [AdguardTeam/Scriptlets#453]
After running tests, we need to open `tests/dist/scriptlets-trusted-set-cookie.html` directly, because old `node-qunit-puppeteer` doesn't detect the error

**Comment by scripthunter7** [comment]
probably https://github.com/AdguardTeam/Scriptlets/issues/448 caused by the same reason

**Comment by AdamWr** [comment]
I have also noticed recently that in Chrome `Set cookie with expires` in `trusted-set-cookie` tests failing, but when running `yarn test` command it's okay (I thought that it was always like that).

If I'm not wrong, it looks like that in Chrome, `document.cookie` is cached, maybe related to this - `https://blog.chromium.org/2024/06/introducing-shared-memory-versioning-to.html`
For example:
```js
document.cookie = "q=w;";
document.cookie = "foo=bar; Max-Age=2";
setInterval(()=>{console.log(document.cookie)},1000);
setTimeout(()=>document.cookie='a=1',5000);
```
In Chrome `foo` cookie is logged until there is change in `document.cookie` (so in this case for 5 seconds) but in Firefox it's not logged immediately when it's removed.

Changing this part:
https://github.com/AdguardTeam/Scriptlets/blob/76c840fe4a63732d748f96811f9209b677bc2774/tests/scriptlets/trusted-set-cookie.test.js#L129-L134
to something like:
```js
setTimeout(() => {
    // It looks like Chrome is caching document.cookie and value is not updated,
    // so as a workaround we remove dummy cookie to force update of document.cookie
    clearCookie('dummyCookie');
    assert.strictEqual(document.cookie.includes(cName), false, 'Cookie name has been deleted');
    assert.strictEqual(document.cookie.includes(cValue), false, 'Cookie value has been deleted');
    clearCookie(cName);
    done();
}, expiresSec * 1000);
```
should fixes it.
