### ISSUE TITLE
Improve 'href-sanitizer' — add ability to modify the value

### ISSUE THREAD

**Issue by slavaleleka** [AdguardTeam/Scriptlets#460]
https://github.com/AdguardTeam/Scriptlets/issues/455#issuecomment-2372755158:
> It'd be best if href's attributes can be modified at the same time.
> 
> For example, every video link in [youtube search result page](https://www.youtube.com/results?search_query=test) has a parameter "pp=[base64 encoded search query]" in it and it can't be got rid of with current options.
> Can we have another option for text and ?parameter to remove parameters in href, like $removeparam considering YouTube can add more private info in it. Sharing raw links from right click copy also exposes how the sharer found the video. $removeparam can only remove parameters after clicking on the link.
>
> Other websites might shove in unnecessary, often tracking parameters as well. So I would like to see a combination of removeparam and href-santinizer

**Comment by AdamWr** [comment]
It would be also nice to have an option to remove hash from the link, a bit related to - https://github.com/AdguardTeam/Scriptlets/issues/135

For example, if there is a link like this one:
```html
<a href="https://example.org/?article#utm_source=Facebook"></a>
```
it should be possible to remove `#utm_source=Facebook`.
