### ISSUE TITLE
Implement requestAnimationFrame scriptlet

### ISSUE THREAD

**Issue by superlex** [AdguardTeam/Scriptlets#47]
Hello,
please, discuss if it can be useful:
https://github.com/gorhill/uBlock/wiki/Resources-Library#raf-ifjs-
https://github.com/gorhill/uBlock/blob/59bdf2b4ccd1151a296af36e5536ed00eeb07fb4/assets/resources/scriptlets.js#L394

**Comment by ameshkov** [comment]
Yeah, we'll implement this one for sure

**Comment by superlex** [comment]
Thanks :D
