### ISSUE TITLE
Yandex Metrika scriptlets and redirects does not help

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/Scriptlets#49]
Steps to reproduce:
- add `@@||mc.yandex.ru/metrika/tag.js$domain=pilotlive.ru,badfilter` to user filter;
- open https://pilotlive.ru/spb#popup:spb
- click "Buy ticket"
<details><summary>Screenshot:</summary> 

![image](https://user-images.githubusercontent.com/8361299/66949254-dd2fcc00-f05e-11e9-88aa-7be571c000c4.png)

 </details>

Actual behavior:
Button is not working with both YM scriptlets or `$redirect` rules
```
||mc.yandex.ru/metrika/tag.js$script,redirect=metrika-yandex-tag
||mc.yandex.ru/metrika/watch.js$script,redirect=metrika-yandex-watch
```

![image](https://user-images.githubusercontent.com/8361299/66949526-5c250480-f05f-11e9-9d27-1cb72fe989c0.png)

**Comment by slavaleleka** [comment]
@Alex-302 could you please check the issue again? for now there are no problems with metrika-yandex-tag redirect, at least on this website it works fine

**Comment by slavaleleka** [comment]
seems like both yandex-metrica redirects works fine for a few recent filters cases [[#50820](https://github.com/AdguardTeam/AdguardFilters/issues/50820), [#49992](https://github.com/AdguardTeam/AdguardFilters/issues/49992)]
