### ISSUE TITLE
Implement scriplet for changing attribute value

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/Scriptlets#51]
On some sites branding can be disabled by removing appropriate class name(replacing `/className/` by emply value). Something like that `document.body.className = document.body.className.replace("branding","");` but for all attributes and elements.

Recent real example - branded table:
https://www.gazeta.ru/sport/?refresh

<details>

![image](https://user-images.githubusercontent.com/8361299/67634515-bc207400-f8c5-11e9-9455-320ed63b6bbb.png)

</details>

after removing `betting` from class name:

<details>

![image](https://user-images.githubusercontent.com/8361299/67634530-e96d2200-f8c5-11e9-8657-638896ce2b3a.png)

</details>

**Comment by ameshkov** [comment]
I think we should try to limit its power and just remove classes.

Let's start with something like this:
`remove-class(selector, className)`

**Comment by Alex-302** [comment]
design can be broken if you remove whole class.

**Comment by ameshkov** [comment]
Not the whole class, I mean removing the specified class

**Comment by Alex-302** [comment]
Ok then. Will it be applicable to all tags?(for example, obfuscated like at some sites)

**Comment by ameshkov** [comment]
I don't know yet:)

I need as many examples as you can provide to figure out what we need.

**Comment by Alex-302** [comment]
At the moment our examples are with className only )

**Comment by ameshkov** [comment]
Then removing a class would be enough.

But I'd still like to see some examples

**Comment by Alex-302** [comment]
https://gist.github.com/Alex-302/194c3300b33071a9d8caa0c9b57e8be2

**Comment by ameshkov** [comment]
So it seems `remove-class` would be enough at this point
