### ISSUE TITLE
VMAP redirect resource

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/Scriptlets#52]
Current VAST redirect resource cannot be applied in case of using VMAP:
https://gist.github.com/Alex-302/4cf5c5eec322b11350fb24dd01b6c8c1

You can test here(French IP is required)
https://www.canalplus.com/divertissement/tpmp-partie-1/h/8946028_50013

**Comment by ameshkov** [comment]
I don't think this can be handled by a $redirect rule. The problem with VMAP is that it contains links to legitimate videos URLs AND the built-in VAST content. In order to get rid of ads, you need to remove VAST from content, but keep video URLs.

**Comment by ameshkov** [comment]
Try replacing it with an empty VMAP using $replace rules, does it help?

**Comment by Alex-302** [comment]
One moment

**Comment by Alex-302** [comment]
Yes. At least on this site.
`||v.fwmrm.net/ad/g/1?*&vpaid=on;$replace=/(<vmap:VMAP[\s\S]*?>)[\s\S]*<\/vmap:VMAP>/\$1<\/vmap:VMAP>/,domain=canalplus.com`
![image](https://user-images.githubusercontent.com/8361299/68025904-b3111780-fcb6-11e9-90cd-f633178111fa.png)

**Comment by ameshkov** [comment]
Let's add a VMAP $redirect then, please come up with a proper desription of this redirect resource and its syntax.

**Comment by Alex-302** [comment]
here are two HARs - before and after replacing
https://mega.nz/#!QNVxkaiL!VdQHkFW5HcbCYBbv7J_gpaKfLoq6S6Fcv2wCOkvkbxM

**Comment by Alex-302** [comment]
```
noopvmap-1.0
Redirects request to an empty VMAP response.

Example:
```
`||example.org^$xmlhttprequest,redirect=noopvmap-1.0`
?

**Comment by ameshkov** [comment]
Yeah, good
