### ISSUE TITLE
Missed description for scriptlets

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/Scriptlets#54]
It seems that there is no description for `noeval` and `prevent-eval-if` scriptlets.

Also `adjust-setInterval` and `adjust-setTimeout` are missed in table of contents and link to `json-prune` seems to not work.

**Comment by AdamWr** [comment]
I guess that descriptions about scriptlets and redirects resources are in rebuild, but I just would like to inform that links to scriptlets/redirects sources don't work.

For example here - https://github.com/AdguardTeam/Scriptlets/blob/master/wiki/about-scriptlets.md#abort-current-inline-script

Link to `Scriptlet source` redirects to https://github.com/AdguardTeam/Scriptlets/blob/master/Volumes/dev/scriptlets/src/scriptlets/abort-current-inline-script.js

**Comment by ameshkov** [comment]
Yeah, @slavaleleka check this out
