### ISSUE TITLE
Issue with abort-current-inline-script

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/Scriptlets#57]
It seems that on this website - [https://www.egyanime.com/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.egyanime.com%2F) - rule like this:
`egyanime.com#%#//scriptlet("abort-current-inline-script", "$", "window.open")`
breaks website.

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/69348756-00a9f000-0c77-11ea-9978-4b946e9eef39.png)

</details>

This script which should be aborted is already commented out and looks like this:
```
<script>
/*
$( "body" ).one( "click", function() {
window.open('','_blank', 'toolbar=no,status=no,menubar=no,scrollbars=no,resizable=no,left=10000, top=10000, width=10, height=10, visible=none', ''); 
});
*/
</script>
```

and I don't see any other `window.open` in website' source, so I think it shouldn't breaks website.

With `AG_abortInlineScript` it works fine (website is not broken):
`egyanime.com#%#AG_abortInlineScript(/window\.open/, '$');`

**Comment by AdamWr** [comment]
Similar case - [https://www.animex.club/izle/detective-conan-iu/1](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://www.animex.club/izle/detective-conan-iu/1)

Rule like this:
`animex.club#%#//scriptlet("abort-current-inline-script", "Math.floor", "babasbmsgx")`
breaks/prevent `Math.floor` function.

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/71996926-5c3b3780-323d-11ea-8df8-408e7693f2ef.png)

</details>

**Comment by AdamWr** [comment]
It looks like that there is one more issue with `abort-current-inline-script`.
For example, if we add rule like this:
`example.org#%#//scriptlet("abort-current-inline-script", "document.body.appendChild", "test")`
then there is an error `Error executing AG js: TypeError: Cannot read property 'appendChild' of null` and other script/scriptlets may not work.

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/72654070-18a7a280-398e-11ea-8b66-377f745baee3.png)

</details>

Link - http://example.org/

**Comment by AdamWr** [comment]
One more issue, this time related to this - https://github.com/AdguardTeam/Scriptlets/issues/42
It seems that on some websites they are doing something like:
```js
function generateContent() {
  return void 0 === generateContent.val && (generateContent.val = " \nwindow.alert('blablabla');");
}

(function () {
  try {
    Object.defineProperty(document.currentScript, "textContent", {
      get: generateContent
    });
  } catch (e) {}

  alert("test");
})();
```
so scriptlet like this:
`f4z.github.io#%#//scriptlet("abort-current-inline-script", "alert", "test")`
doesn't work.

Example link - https://f4z.github.io/Test/index.html
There are two alerts on this website - `alert("test");` and `alert("test1");`, but only the second is blocked by mentioned rule.

**Comment by AdamWr** [comment]
Probably one more issue.
It seems that reCAPTCHA is broken on this website -  [https://dl1.win10.vn/u5cqEKpe](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fdl1.win10.vn%2Fu5cqEKpe) by rule like this:
```
win10.vn#%#//scriptlet("abort-current-inline-script", "document.createElement", "ignielAdBlock")
```

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/81172374-63c9dd80-8f9e-11ea-9e04-490c2746ed75.png)

</details>

**Comment by slavaleleka** [comment]
that issue on `dl1.win10.vn` happens because of their implementation of recaptcha

**Comment by AdamWr** [comment]
Probably one more case -  [https://www.meuwindows.com/solucao-facebook-lento-no-google-chrome/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.meuwindows.com%2Fsolucao-facebook-lento-no-google-chrome%2F)

Rule like this:
`meuwindows.com#%#//scriptlet("abort-current-inline-script", "jQuery", "ai_adb")`
breaks website (images don't load).

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/88536812-bac6d800-d00c-11ea-955d-1f259b2b9fdf.png)

</details>

It seems that it "abort" whole `jQuery` function.
<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/88536923-e47fff00-d00c-11ea-9052-ed13b42d282e.png)

</details>

**Comment by AdamWr** [comment]
The same issue as in https://github.com/AdguardTeam/Scriptlets/issues/57#issuecomment-664341549 on this website -  [https://dramahd.me/its-okay-to-not-be-okay/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fdramahd.me%2Fits-okay-to-not-be-okay%2F)

Rule:
`dramahd.me#%#//scriptlet("abort-current-inline-script", "jQuery", "ai_adb")`

**Comment by AdamWr** [comment]
Similar issue as in https://github.com/AdguardTeam/Scriptlets/issues/57#issuecomment-664341549
Website - [https://manga1000.com/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fmanga1000.com%2F%25e3%2580%2590%25e7%25ac%25ac1%25e8%25a9%25b1%25e3%2580%2591%25e4%25bf%25ba%25e3%2581%25ae%25e3%2580%258e%25e9%2591%2591%25e5%25ae%259a%25e3%2580%258f%25e3%2582%25b9%25e3%2582%25ad%25e3%2583%25ab%25e3%2581%258c%25e3%2583%2581%25e3%2583%25bc%25e3%2583%2588%25e3%2581%2599%25e3%2581%258e%25e3%2581%25a6-raw%2F)
Rule:
`manga1000.com#%#//scriptlet("abort-current-inline-script", "onload", "Ad Block")`

**Comment by AdamWr** [comment]
Another similar case.
Add these rule:
```
adamwr.github.io#%#//scriptlet("abort-current-inline-script", "atob", "VGVzdA")
adamwr.github.io#%#AG_onLoad(function() { console.log(atob("V2hhdGV2ZXI=")); });
```

Go here - https://adamwr.github.io/test-page/inline.html
`abort-current-inline-script` should prevent only inline script, but it seems that it breaks `atob` function.

By the way, code of this website looks like this:
```html
<body>
   <script src="test1.js"></script>
   <script>
      console.log(atob("VGVzdA=="));
   </script>
</body>
```
and if I move `<script src="test1.js"></script>` below inline script then it works fine - https://adamwr.github.io/test-page/inline_test.html

<details><summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/29142494/93992503-ec9ab780-fd8d-11ea-9736-8456bfacbf38.png)

![image](https://user-images.githubusercontent.com/29142494/93992534-f6bcb600-fd8d-11ea-889b-ab35834ac8a2.png)

</details>

**Comment by AdamWr** [comment]
I'm not sure, but it seems that the problem is with this part:
```js
if (!document.currentScript) {
            const scripts = document.getElementsByTagName('script');
            return scripts[scripts.length - 1];
        }
```
https://github.com/AdguardTeam/Scriptlets/blob/master/src/scriptlets/abort-current-inline-script.js#L76-L82

If I understand correctly this check is necessary for IE, because it doesn't support `document.currentScript`.
Changing `if (!document.currentScript)`  to something like `if (!"currentScript" in document)` (like is done in `AG_abortInlineScript`) seems to works fine, but it's still broken in IE.

**Comment by ameshkov** [comment]
@slavaleleka please take a closer look when you're back from vacation

**Comment by Alex-302** [comment]
Probably the same issue. Player is broken in AdGuard, but not in uBO:
https://www.zive.cz/clanky/tyden-zive-zalohujte-deti-do-cloudu-vse-ostatni-je-ruska-ruleta/sc-3-a-206135/default.aspx
`zive.cz#%#//scriptlet('ubo-acis.js', 'String.fromCharCode')`
Disable Base filter or exclusion before check.

**Comment by AdamWr** [comment]
And one more issue related to this - https://github.com/AdguardTeam/Scriptlets/issues/42, https://github.com/AdguardTeam/Scriptlets/issues/57#issuecomment-593638991

Example script:
```js
!function () {
  var t,
      e = window.document;

  try {
    (t = e.currentScript).textContent = "";
  } catch (t) {}

  try {
    t[parentNode][removeChild](t);
  } catch (t) {}

  alert("test");
}();
```

Rule:
`adamwr.github.io#%#//scriptlet("abort-current-inline-script", "alert", "test")`
Test website - https://adamwr.github.io/test-page/acinline.html

There are two alerts on this website - `alert("test")` and `alert("test1")`, but only the second one is "blocked" by mentioned rule.

**Comment by AdamWr** [comment]
If I'm not wrong, this issue wasn't reported yet.
Steps to reproduce:
1. Add these rules:
```
adamwr.github.io#%#//scriptlet("abort-current-inline-script", "atob", "VGVzdA")
adamwr.github.io#%#//scriptlet("abort-current-inline-script", "atob", "test")
```
2. Go here - https://adamwr.github.io/test-page/inline_test.html

On this website there is code like this:
```
console.log(atob("VGVzdA=="));
```
so first rule should abort it, but it doesn't work when second rule is added.


<details><summary>Screenshot with both rules:</summary>

![image](https://user-images.githubusercontent.com/29142494/116006273-ccc0c000-a60a-11eb-9446-24e1bd830277.png)

</details>

<details><summary>Screenshot with second rule (adamwr.github.io#%#//scriptlet("abort-current-inline-script", "atob", "test")) disabled:</summary>

![image](https://user-images.githubusercontent.com/29142494/116006324-04c80300-a60b-11eb-91f7-c7239fa7e25b.png)

</details>

**Comment by ameshkov** [comment]
> If I'm not wrong, this issue wasn't reported yet.

Unfortunately, this is by design and changing it is not about improving a single scriptlet, but about changing scriptlets design.

**Comment by AdamWr** [comment]
Uh, okay.

By the way, any chance for fixing this issue (soon)? - https://github.com/AdguardTeam/Scriptlets/issues/57#issuecomment-699664285
