### ISSUE TITLE
'remove-attr' scriptlet executes only once

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/Scriptlets#62]
In some cases it does not dive expected result. 
For example on it does not remove `style` attribute on `body`
https://vgtimes.ru/news/62663-modder-dobavil-v-minecraft-malysha-yodu-on-ochen-milyy-i-pomogaet-igroku-s-pomoschyu-sily.html
`vgtimes.ru#%#//scriptlet("remove-attr", "style", "#loading-layer")`

Add exclusions before testing:
`vgtimes.ru#@%#//scriptlet("set-constant", "adblock_background_data", "null")`
`vgtimes.ru#@%#AG_setConstant("adblock_background_data", "undefined");`

**Comment by uBlock-user** [comment]
I made one  using `MutationObserver` for running it untill the entire page load completes -- https://github.com/uBlock-user/uBO-Scriptlets/blob/master/scriptlets.txt#L104

**Comment by ameshkov** [comment]
Tbh, I don't see why this shouldn't be the default behavior of the `remove-attr` scriptlet.

**Comment by uBlock-user** [comment]
Probably because cases where my version is required are very few. I made mine after I came across a case where the default one wouldn't work.

**Comment by ameshkov** [comment]
Well, the overhead of maintaining a MutationObserver and re-evaluating the scriptlet is close to zero (especially if we add throttling with a short 10-20ms period).

Even though these cases might be relatively rare, I think this will make the scriptlet more consistent.

**Comment by uBlock-user** [comment]
Is there any performance issue in my version that you can see ?

**Comment by ameshkov** [comment]
The only thing I'd consider doing is adding throttling for the MutationObserver callback, something like this:

```javascript
function throttle (callback, limit) {
  var wait = false;
  return function () {
    if (!wait) {

      callback.apply(null, arguments);
      wait = true;
      setTimeout(function () {
        wait = false;
      }, limit);
    }
  }
}
...
const observer = new MutationObserver(throttle(rmattr, 20));
...
```
