### ISSUE TITLE
Improve googlesyndication-adsbygoogle.js

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/Scriptlets#67]
At the moment `googlesyndication-adsbygoogle.js` is appending `iframe` to `document.body`, but there are some websites which check if there is an `iframe` as a child of `.adsbygoogle` element.
<details><summary>Example:</summary>

```javascript
var antiadblock1 = function () {
  var elements = document.getElementsByClassName("adsbygoogle");

  if (elements.length == 0) {
    return;
  }

  if (!elements[0].getElementsByTagName("IFRAME").length) {
    alert("adblock");
  }
}();
```

</details>

So maybe instead of [document.body.appendChild(frame);](https://github.com/AdguardTeam/Scriptlets/blob/master/src/redirects/googlesyndication-adsbygoogle.js#L35) we can use something like `adElems[i].appendChild(frame);`?
If I'm not wrong, this is default behavior when `https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js` is not blocked.

Also some websites checking if `.adsbygoogle` has attribute `data-adsbygoogle-status`.
<details><summary>Example:</summary>

```javascript
var antiadblock2 = function () {
  var elements = document.getElementsByClassName("adsbygoogle");

  if (elements.length == 0) {
    return;
  }

  if (!elements[0].hasAttribute("data-adsbygoogle-status")) {
    alert("adblock");
  }
}();
```

</details>

What about adding something like `adElems[i].setAttribute('data-adsbygoogle-status', 'done');`?
It seems that this is also default behavior when `https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js` is not blocked.

**Comment by AdamWr** [comment]
I'm not sure if it's a bug or by design, but it seems that sometimes there is a lot of iframes appended to `.adsbygoogle`
<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/79670455-82b92900-81c3-11ea-9d16-e7388d2f2b7b.png)

</details>

Shouldn't there be only two frames (one with `aswift_` and second with `google_ads_iframe_`)?

Steps to reproduce:
1. Add this rule:
```
||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$redirect=googlesyndication-adsbygoogle
```
2. Go to this website -  [https://www.androidpolice.com/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://www.androidpolice.com/)

**Comment by ameshkov** [comment]
Yeah, this definitely looks weird

**Comment by AdamWr** [comment]
One more question regarding `googlesyndication-adsbygoogle.js`.
There is a code like this:
```javascript
window.adsbygoogle = window.adsbygoogle || {
        length: 0,
        loaded: true,
        push() {
            this.length += 1;
        },
    };
```

Does this part `window.adsbygoogle ||` is really needed?
I mean that on some websites `adsbygoogle` is already declared.
For example on [https://www.androidpolice.com/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://www.androidpolice.com/), there is code like this:
```javascript
if(!ap_scrolluser){
   (adsbygoogle = window.adsbygoogle || []).push({});
}
```
so `adsbygoogle` will not be changed.

Some websites are checking if `adsbygoogle.loaded` is equal to `true` to detect ad blockers and sometimes these websites contain similar script like on `androidpolice.com`, so using `||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$redirect=googlesyndication-adsbygoogle` may be not enough.

From what I can see, if `https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js` is not blocked then `adsbygoogle` is anyway changed.

By the way, it seems that there is one unnecessary comma (`,`), I think - https://github.com/AdguardTeam/Scriptlets/blob/master/src/redirects/googlesyndication-adsbygoogle.js#L25

**Comment by ameshkov** [comment]
Makes perfect sense

**Comment by AdamWr** [comment]
And maybe one more thing. Sometimes websites checking `contentWindow.length` of `iframe`, something like:
```javascript
if (document.querySelector(`ins.adsbygoogle iframe`).contentWindow.length < 1) {
  alert("Adblock");
}
```

What about creating an `iframe` in current `iframe`?
Something like this:
```javascript
var iframeInAswiftIframe = adElems[i].querySelector("#" + aswiftIframe.id);
var crateIframeInAswiftIframe = document.createElement("iframe");
iframeInAswiftIframe.contentWindow.document.body.appendChild(crateIframeInAswiftIframe);
```
Just an example:
<details><summary>Code:</summary>

```javascript
[...]
if (!areIframesDefined) {
            // here we do the job if scriptlet has not been executed earlier
            adElems[i].setAttribute(statusAttrName, 'done');

            const aswiftIframe = document.createElement('iframe');
            aswiftIframe.id = `${ASWIFT_IFRAME_MARKER}${i + 1}`;
            aswiftIframe.style = css;
            adElems[i].appendChild(aswiftIframe);
           
            // create iframe in iframe
            var iframeInAswiftIframe = adElems[i].querySelector("#" + aswiftIframe.id);
            var crateIframeInAswiftIframe = document.createElement("iframe");
      	    iframeInAswiftIframe.contentWindow.document.body.appendChild(crateIframeInAswiftIframe);

            const googleadsIframe = document.createElement('iframe');
            googleadsIframe.id = `${GOOGLE_ADS_IFRAME_MARKER}${i + 1}`;
            googleadsIframe.style = css;
            adElems[i].appendChild(googleadsIframe);
		
           // create iframe in iframe	
           var iframeInGoogleadsIframe = adElems[i].querySelector("#" + googleadsIframe.id);
           var crateIframeInGoogleadsIframe = document.createElement("iframe");
      	   iframeInGoogleadsIframe.contentWindow.document.body.appendChild(crateIframeInGoogleadsIframe);
          
            executed = true;
        }
[...]
```

</details>

**Comment by slavaleleka** [comment]
@AdamWr could you please give some examples of websites where `adsbygoogle.loaded` and `contentWindow.length` are checked?

**Comment by AdamWr** [comment]
`adsbygoogle.loaded` is checked on [https://www.freetutorialsus.com/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://www.freetutorialsus.com/)
We already have `freetutorialsus.com#%#//scriptlet("set-constant", "adsbygoogle.loaded", "true")` to fix it.
It seems that it was also on [https://moroa.tistory.com/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://moroa.tistory.com/), but now this code is commented out.

As far as I know, checking `contentWindow.length` is not so popular, but it's checked on [https://extremereportbot.com/report/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://extremereportbot.com/report/)
This website also checking `ga.length`, which is related to this issue - https://github.com/AdguardTeam/Scriptlets/issues/91

**Comment by AdamWr** [comment]
One more website which checks `adsbygoogle.loaded` - [https://alphaantileak.net/ads.html](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://alphaantileak.net/ads.html)
