### ISSUE TITLE
'remove-attr' is not working as it should

### ISSUE THREAD

**Issue by zloyden** [AdguardTeam/Scriptlets#70]
https://cloud.mail.ru/public/2L1N/4tPpCsp7c/Foto/ -> refresh page one time.
This scriptlet `cloud.mail.ru#%#//scriptlet("remove-attr", "href", ".public_folder > div.w-public__content + div[style] > a[target="_blank"]")` must remove attribute `href` but it doesn't work.
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/33488229/75557814-cc05bb80-5a51-11ea-83ce-27a53c8a1e99.png)

</details><br/>

**Comment by slavaleleka** [comment]
there is a mistake in the rule — you should not use the same type of quotes for defining the parameter and inside it. so valid rule will be:
```
cloud.mail.ru#%#//scriptlet("remove-attr", "href", ".public_folder > div.w-public__content + div[style] > a[target='_blank']")
```
or 
```
cloud.mail.ru#%#//scriptlet('remove-attr', 'href', '.public_folder > div.w-public__content + div[style] > a[target="_blank"]')
```

* * *

for now, even with proper syntax, `remove-attr` might not work fine if the attribute is being added dynamically after the page has been loaded. soon it will be fixed

**Comment by zloyden** [comment]
> for now, even with proper syntax, `remove-attr` might not work fine if the attribute is being added dynamically after the page has been loaded. soon it will be fixed

I also tried (before create an issue) with another syntax as you showed in quote - it worked only once.

> for now, even with proper syntax, remove-attr might not work fine if the attribute is being added dynamically after the page has been loaded. soon it will be fixed

I guess that is our case. I'll be waiting for fix:)
