### ISSUE TITLE
Handle 'prevent-window-open' changes in UBO scriptlets

### ISSUE THREAD

**Issue by slavaleleka** [AdguardTeam/Scriptlets#75]
[gorhill has improved `window.open-defuser` scriptlet](https://github.com/gorhill/uBlock/commit/b27848a060eee961e2403192097448467b3bc7b5) and its new syntax deprecates the old one

~~but there is not a single rule with new syntax in any filter list, so there is no need to handle these changes~~ 
the ubo-filters contain new syntax rules now, and they support both types of syntax
* * *
add `nowoif.js` to aliases and update compatibility table

**Comment by AdamWr** [comment]
I think that it may be related to this issue - https://github.com/AdguardTeam/Scriptlets/issues/71
