### ISSUE TITLE
"log-addEventListener" breaks some websites

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/Scriptlets#76]
Steps to reproduce:
1. Add this rule:
`themarker.com#%#//scriptlet("log-addEventListener")`
or
`themarker.com#%#//scriptlet('ubo-aeld.js', '', 'clientHeight')`
2. Go here -  [https://www.themarker.com/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.themarker.com%2F)

Website is blank.

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/78032037-ac212a80-7364-11ea-8a67-0dd53fe27a51.png)

</details>

**Comment by ameshkov** [comment]
Yeah, this s a bug. It should be rather easy to fix, though.
