### ISSUE TITLE
Few minor issues in descriptions

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/Scriptlets#77]
1. Example for `abort-on-property-write` scriptlet is incorrect.

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/78424715-ae8ac980-766f-11ea-88b8-6f652c5def74.png)

</details>

https://github.com/AdguardTeam/Scriptlets/blob/master/wiki/about-scriptlets.md#-%EF%B8%8F-abort-on-property-write

<hr>

2. There is no example for `prevent-eval-if` scriptlet.

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/78424746-dc700e00-766f-11ea-8f84-3ef5067af5f7.png)

</details>

https://github.com/AdguardTeam/Scriptlets/blob/master/wiki/about-scriptlets.md#-%EF%B8%8F-prevent-eval-if

<hr>

3. If I'm not wrong, example for `remove-class` is partly not correct.

The example looks like that:
`example.org#%#//scriptlet('remove-class', 'branding', 'div[class="inner"]')`

```
<!-- before -->
<div class="wrapper true branding">
    <div class="inner bad branding">Some text</div>
</div>
```

If I understand correctly, it should be `div[class^="inner"]`  instead of `div[class="inner"]`, because in example there is no `class="inner"` but `class="inner bad branding"`.

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/78424813-3670d380-7670-11ea-9020-7681dc1b1abc.png)

</details>

https://github.com/AdguardTeam/Scriptlets/blob/master/wiki/about-scriptlets.md#-%EF%B8%8F-remove-class

**Comment by ameshkov** [comment]
@slavaleleka let's update this

**Comment by AdamWr** [comment]
One more issue in description.
It seems that last two examples in `prevent-window-open` scriptlet documentation are incorrect - https://github.com/AdguardTeam/Scriptlets/blob/master/wiki/about-scriptlets.md#-%EF%B8%8F-prevent-window-open

```
5. Prevent all window.open calls and return 'trueFunc' instead of it if website checks it:
example.org#%#//scriptlet('prevent-window-open', , , 'trueFunc')
```

I think that it should be something like this:
`example.org#%#//scriptlet('prevent-window-open', '1', '', 'trueFunc')`

The same for the last example:
`example.org#%#//scriptlet('prevent-window-open', '1', , '{propName=noopFunc}')`
If I'm not wrong, it should be:
`example.org#%#//scriptlet('prevent-window-open', '1', '', '{propName=noopFunc}')`
