### ISSUE TITLE
Improve uBO compatibility

### ISSUE THREAD

**Issue by superlex** [AdguardTeam/Scriptlets#78]
Hello,
[Scriptlets compatibility](https://github.com/AdguardTeam/Scriptlets/blob/master/wiki/compatibility-table.md#-scriptlets-compatibility-table) should be improved as regards uBO: for example,
`[AG] abort-current-inline-script`
should be compatible with 
```
[uBO] abort-current-inline-script.js
[uBO] abort-current-inline-script
[uBO] acis.js
[uBO] acis
```
Currently, it looks like
```
[uBO] abort-current-inline-script
[uBO] acis
```
don't work.

**Comment by slavaleleka** [comment]
@superlex 
could you please specify what exactly rules you tried and where?

**Comment by superlex** [comment]
@slavaleleka 
Try here
https://testcases.adguard.com/Filters/scriptlet-rules/test-scriptlet-rules.html?testId=83bd0cb2
```
! 1
testcases.adguard.com,surge.sh##+js(abort-current-inline-script.js, __testCase4)
! 2
testcases.adguard.com,surge.sh##+js(abort-current-inline-script, __testCase4)
! 3
testcases.adguard.com,surge.sh##+js(acis.js, __testCase4)
! 4
testcases.adguard.com,surge.sh##+js(acis, __testCase4)
```
Only 1 and 3 work.
