### ISSUE TITLE
Implement set-cookie scriptlet

### ISSUE THREAD

**Issue by slavaleleka** [AdguardTeam/Scriptlets#79]
https://github.com/NanoAdblocker/NanoCore2/blob/master/src/snippets.js

(it was mentioned in [other issue](https://github.com/AdguardTeam/Scriptlets/issues/23))

**Comment by ameshkov** [comment]
It is dangerous to provide an option to set an arbitrary cookie.

What about the same approach as with `set-constant`? The question is what rules are there for set cookie scriptlet?

**Comment by slavaleleka** [comment]
I suppose that it can be made in such way:

**`example.org#%#//scriptlet("set-cookie", name, value[, path])`**
- name — required — cookie name to be set
- value — required. possible values (the most common, ): 
  - 1 / 0 (or number >= 0 && < 15)
  - true / True
  - false
  - yes / Yes / Y
  - no
  - ok / OK
- path ( ? ) — optional — defaults to '/' (root path). or maybe it's not needed at all because there are set-cookie js-rules only with `path=/;`

**Comment by ameshkov** [comment]
@slavaleleka makes sense
