### ISSUE TITLE
abort-current-inline-script may prevents other scriptlets

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/Scriptlets#87]
Steps to reproduce
1. Add these rules:
```
adamwr.github.io#%#//scriptlet("abort-current-inline-script", "addEventListener", "Test")
adamwr.github.io#%#//scriptlet("prevent-addEventListener", "load", "Test2")
```
**It seems that order is important in this case, so please do not change it.**

2. Go here - https://adamwr.github.io/test-page/event.html

There is an inline script like this:
```
window.addEventListener('load' , function () {
        console.log("addEventListener - Test");
})
```

and another script - https://adamwr.github.io/test-page/test.js, which looks like this:
```
window.addEventListener('load' , function () {
        console.log("addEventListener - Test2");
})
```

So, without scriptlets from first step, there should be two messages in console:
```
addEventListener - Test
addEventListener - Test2
```

With scriptlets enabled, both messages should be blocked, first one by `abort-current-inline-script`, second by `prevent-addEventListener`, but for some reason second rule doesn't work.
Second rule works fine if `abort-current-inline-script` scriptlet is disabled.

**Comment by ameshkov** [comment]
I am not sure if we'll be able to fix this properly

**Comment by AdamWr** [comment]
It seems that it may also prevents extended CSS rules.
Steps to reproduce
1. Add these rules:
```
example.org#?#body
example.org#%#//scriptlet("abort-current-inline-script", "document.querySelectorAll", "popMagic")
```
2. Go here - http://example.org/

Website should be blank, but it seems that extended CSS rule doesn't work.

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/83152646-5a93e280-a0fe-11ea-93d5-e97ce52da527.png)

</details>

It happens with app only, with extension I can't reproduce it.

**Comment by ameshkov** [comment]
@slavaleleka 

In the `abort-current-inline-script`:
1. Save the current `document.currentScript` value
2. When it's time to abort - check that `document.currentScript` is not the same script
