### ISSUE TITLE
Implement nowebrtc scriptlet

### ISSUE THREAD

**Issue by timirila1** [AdguardTeam/Scriptlets#9]
Name: `nowebrtc`
Aliases: `ubo-nowebrtc.js`

**Links**
[UBO docs](https://github.com/gorhill/uBlock/wiki/Resources-Library#nowebrtcjs-)
[UBO code](https://github.com/uBlockOrigin/uAssets/blob/80b195436f8f8d78ba713237bfc268ecfc9d9d2b/filters/resources.txt#L1308)

**Comment by Bluscream** [comment]
Isnt no webrtc already in stealth mode?

**Comment by timirila1** [comment]
@Bluscream this is for compatibility purposes.
