### ISSUE TITLE
Add 'empty' redirect

### ISSUE THREAD

**Issue by slavaleleka** [AdguardTeam/Scriptlets#92]
as alias for ubo's one

(check `redirectableResources` on [ubo redirect list](https://raw.githubusercontent.com/gorhill/uBlock/master/src/js/redirect-engine.js))

**Comment by ameshkov** [comment]
Shouldn't be simply an alias to nooptext? empty resource is originally our $empty modifier after all.

**Comment by slavaleleka** [comment]
there are some extra checking for source type specified for 'empty' redirect. I suppose we should handle it for better compatibility
