### ISSUE TITLE
wcslog.js redirect

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/Scriptlets#94]
@adguard-bot commented on [Wed Sep 02 2020](https://github.com/AdguardTeam/AdguardFilters/issues/62932)

### Issue URL (Incorrect Blocking)
 [https://m.place.naver.com/my/review/5f17e09118deb00010dddd11?v=2](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fm.place.naver.com%2Fmy%2Freview%2F5f17e09118deb00010dddd11%3Fv%3D2)
### Comment
Username: @ab-c-d
> This is caused by a rule `||naver.net/wcslog.js$domain=~m.tv.naver.com` in AG tracking protection filter.
> 
> In old List-KR filter, there was a rule  `#%#window.wcs_add = {}; window.wcs_do = function() { };` to fix this. In current List-KR, there isn't. Instead of whitelisting for this site, one can create a redirection rule for `wcslog.js` as what's done for `ga.js`, containing this `window.wcs_add = {};, window....` rule.
> --
> The information below is automatically generated. Do not delete it.
> 
> Referrer:
> https://m.place.naver.com/my/5f4f5be06c3d7f733422debe
> 
> Custom userscripts:
> C:\Users\SooHong\Desktop\scihub.user.js
> https://gist.github.com/seanl-adg/a105f3ffbbf9a34d2c0cf54cca406289/raw/0133b70d25b6bb39048f938a36b51b5233b39c5d/github-show-recent-updated-issues-by-default.user.js
> https://gist.githubusercontent.com/nanikit/6b13d447006e802b393e5598516a42e6/raw/manamoa.user.js
> C:\Users\SooHong\Softwares\Web filters\naver_dict.user.js
> https://userscripts.adtidy.org/release/popup-blocker/2.5/popupblocker.user.js
> https://userscripts.adtidy.org/release/assistant/4.3/assistant.user.js
> 

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/PClDabL.png)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/BgUf4ai.jpg)
</details>

**Comment by Alex-302** [comment]
redirect rule can be general, scriptlet - not.

**Comment by Alex-302** [comment]
will replace current rules by scriptlets, and leave @@ for CB only

**Comment by slavaleleka** [comment]
`noopFunc` is already supported by set-constant. but we should extend it for `noopObj` (empty object) and `noopArr` (empty array, might come in handy)

**Comment by slavaleleka** [comment]
[`set-constant`](./../master/wiki/about-scriptlets.md#set-constant) was extended to support `emptyArr` and `emptyObj` in [v1.3.4](https://github.com/AdguardTeam/Scriptlets/releases/tag/v1.3.4)

**Comment by AdamWr** [comment]
It looks like that `set-constant` is not enough now.
For example, here - https://github.com/AdguardTeam/AdguardFilters/issues/111052
and here - https://github.com/AdguardTeam/AdguardFilters/issues/54299

To reproduce add:
```
||wcs.naver.net/wcslog.js$important
```
to user rules and navigate to - [https://privatenote.co.kr/main_studying/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fprivatenote.co.kr%2Fmain_studying%2F)
Or to - [https://www.adpiamall.com/home](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.adpiamall.com%2Fhome)

So, maybe we could reconsider to add a redirect resource for `wcslog.js`?

Something like this should fix both issues:
```js
(function () {
  window.wcs_add = {};
  window.wcs_do = function() {};
  window.wcs = {
    inflow(){},
  }
})();
```
