### ISSUE TITLE
Add support for UBO $redirect-rule modifier

### ISSUE THREAD

**Issue by maximtop** [AdguardTeam/Scriptlets#95]
https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#redirect-rule

**Comment by slavaleleka** [comment]
related: [CoreLibs#1303](https://github.com/AdguardTeam/CoreLibs/issues/1303)

**Comment by slavaleleka** [comment]
done in [tsurlfilter](https://github.com/AdguardTeam/tsurlfilter)
