### ISSUE TITLE
Change `remove-attr.js` short name

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/Scriptlets#97]
`ra.js` to `ra`
https://github.com/gorhill/uBlock/wiki/Resources-Library#remove-attrjs-
and check all other.
Also required changes in rules validation/conversion.

**Comment by krystian3w** [comment]
Loop in own scriptlets maybe generate breakage in uBO - uBO no have plans to implement loop for:

* `remove-attr` (`ra`) and
* `remove-class` (`rc`)

**Comment by ameshkov** [comment]
> Loop

What kind of loop do you mean?

**Comment by krystian3w** [comment]
Detect dom nodes changes if filter no repair problem after all page was loaded:

> Removes the specified attributes from DOM nodes. This scriptlet runs once when the page loads and **after that periodically in order to DOM tree changes**.

uBO version of these scriptles no check any dom changes: 

https://github.com/AdguardTeam/AdguardFilters/issues/63062#issuecomment-706723616

**Comment by ameshkov** [comment]
Tbh I don't understand why uBO version does not do this as well. Detecting changes is not a heavy operation and this is really useful.

**Comment by krystian3w** [comment]
Probably because the repair scrolling of CSS is more lightweight.

**Comment by ameshkov** [comment]
Hm, I don't see what's the connection to scrolling or CSS here.

**Comment by krystian3w** [comment]
On Facebook @BlazDT  repair scroll with `remove-class`, but uBO no detect dom nodes changes, so scroll is still locked.

uBO can use these idea:
`##.hasCookieBanner > div[id][class][style]:nth-child(2):nth-of-type(1):style(position: static !important;)`

If the "compressed" class `._31e` is very stable also possible change:

`div[id][class][style]:nth-child(2):nth-of-type(1)` to simple `._e31`.

For the facebook interface, CSS will certainly be lighter (legacy PC with very old AMD/Intel processors from 2000-2010).

**Comment by ameshkov** [comment]
Ah, you're comparing CSS rules to remove-class. You're right then, CSS rules would be lighter indeed.

**Comment by krystian3w** [comment]
I found only one fictitious example with an advertising blockade, but the site is 'unpopular' and worked effectively with a `set-constant`.

As the webmarster creators have followed the issues of uBO and AG about that page, they will certainly block both methods of hiding the advert slider.

**Comment by slavaleleka** [comment]
> Change `ra.js` to `ra`

we already handle short ubo scriptlets names while conversion. and it seems that with latest version of compiler they have been converting properly:
```
! Rule "super.cz##+js(ra, style, body)" converted to: "super.cz#%#//scriptlet('ubo-ra.js', 'style', 'body')"
! Rule "akamai.com##+js(ra, class, .disable-sibling-pointer-events)" converted to: "akamai.com#%#//scriptlet('ubo-ra.js', 'class', '.disable-sibling-pointer-events')"
! Rule "ithardware.pl##+js(ra, href, a.authorlink[href="#"])" converted to: "ithardware.pl#%#//scriptlet('ubo-ra.js', 'href', 'a.authorlink[href="#"]')"
```
