### ISSUE TITLE
Wrongly converted scriptlet rule

### ISSUE THREAD

**Issue by slavaleleka** [AdguardTeam/Scriptlets#99]
@ameshkov commented on [Thu Jun 11 2020](https://github.com/AdguardTeam/FiltersCompiler/issues/83)

I found bug with CJX:

```
! dlkoo.com#%#//scriptlet('ubo-acis,setTimeout,testad.js') is excluded by "#%#//scriptlet" in exclusions-low.txt
dlkoo.com#%#//scriptlet('ubo-acis,setTimeout,testad.js')
```

Origin allow not use spaces:

`dlkoo.com##+js(acis,setTimeout,testad)`

_Originally posted by @krystian3w in https://github.com/AdguardTeam/FiltersCompiler/issues/52#issuecomment-642854883_

**Comment by slavaleleka** [comment]
Scriptlet parameters in UBO rule should be separated by comma + space. Otherwise, the rule is not valid

And we will not handle no-space rules because such fix will cause bigger problems

**Comment by krystian3w** [comment]
So CJX no test any scriptlet rule?

**Comment by krystian3w** [comment]
for my this works:

`gorhill.github.io##+js(nostif,bad)`

on

https://gorhill.github.io/uBlock/tests/scriptlet-injection-filters-1.html

![obraz](https://user-images.githubusercontent.com/35370833/96913871-809e9280-14a4-11eb-960f-4123c8e83efb.png) |
--- |
